CREATE TABLE Team (
		id INTEGER NOT NULL,
		name VARCHAR(255) NOT NULL,
		city VARCHAR(255) NOT NULL
	);

CREATE TABLE Vehicle (
		model VARGRAPHIC(255) NOT NULL,
		year INTEGER NOT NULL,
		id BIGINT NOT NULL,
		desc VARGRAPHIC(255) NOT NULL,
		make VARGRAPHIC(255) NOT NULL,
		horsePower INTEGER NOT NULL
	);

CREATE TABLE Player (
		id INTEGER NOT NULL,
		name VARCHAR(255) NOT NULL,
		pos INTEGER NOT NULL,
		salary DOUBLE NOT NULL,
		team_id INTEGER
	);

ALTER TABLE Vehicle ADD CONSTRAINT Vehicle_PK PRIMARY KEY (id);

ALTER TABLE Player ADD CONSTRAINT Player_PK PRIMARY KEY (id);

ALTER TABLE Team ADD CONSTRAINT Team_PK PRIMARY KEY (id);

