ALTER TABLE Players DROP CONSTRAINT Players_PK;

ALTER TABLE Vehicle DROP CONSTRAINT Vehicle_PK;

ALTER TABLE Teams DROP CONSTRAINT Teams_PK;

DROP TABLE Teams;

DROP TABLE Players;

DROP TABLE Truck;

DROP TABLE Vehicle;

CREATE TABLE Teams (
		TEAM_NAME VARGRAPHIC(255) NOT NULL,
		TEAM_ID INTEGER NOT NULL,
		TEAM_CITY VARGRAPHIC(255) NOT NULL
	);

CREATE TABLE Players (
		LAST_NAME VARGRAPHIC(255) NOT NULL,
		PLAYER_ID INTEGER NOT NULL,
		DRAFT_DATE DATE NOT NULL,
		ANNUAL_SALARY DOUBLE NOT NULL,
		TEAM_ID INTEGER NOT NULL,
		FIRST_NAME VARGRAPHIC(255) NOT NULL
	);

CREATE TABLE Truck (
		make VARGRAPHIC(255) NOT NULL,
		horsePower INTEGER NOT NULL
	);

CREATE TABLE Vehicle (
		id BIGINT NOT NULL,
		desc VARGRAPHIC(255) NOT NULL
	);

ALTER TABLE Players ADD CONSTRAINT Players_PK PRIMARY KEY (PLAYER_ID);

ALTER TABLE Vehicle ADD CONSTRAINT Vehicle_PK PRIMARY KEY (id);

ALTER TABLE Teams ADD CONSTRAINT Teams_PK PRIMARY KEY (TEAM_ID);

delete from player where id=112
