package hoshen.xsm.lightsoft.corba.CosTrading.LinkPackage;


/**
* hoshen/xsm/lightsoft/corba/CosTrading/LinkPackage/LimitingFollowTooPermissiveHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from lightsoft/CosTrading.idl
* 13:11:20 GMT+02:00 יום חמישי 28 יוני 2007
*/

abstract public class LimitingFollowTooPermissiveHelper
{
  private static String  _id = "IDL:omg.org/CosTrading/Link/LimitingFollowTooPermissive:1.0";

  public static void insert (org.omg.CORBA.Any a, hoshen.xsm.lightsoft.corba.CosTrading.LinkPackage.LimitingFollowTooPermissive that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static hoshen.xsm.lightsoft.corba.CosTrading.LinkPackage.LimitingFollowTooPermissive extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = hoshen.xsm.lightsoft.corba.CosTrading.FollowOptionHelper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "limiting_follow_rule",
            _tcOf_members0,
            null);
          _tcOf_members0 = hoshen.xsm.lightsoft.corba.CosTrading.FollowOptionHelper.type ();
          _members0[1] = new org.omg.CORBA.StructMember (
            "max_link_follow_policy",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_exception_tc (hoshen.xsm.lightsoft.corba.CosTrading.LinkPackage.LimitingFollowTooPermissiveHelper.id (), "LimitingFollowTooPermissive", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static hoshen.xsm.lightsoft.corba.CosTrading.LinkPackage.LimitingFollowTooPermissive read (org.omg.CORBA.portable.InputStream istream)
  {
    hoshen.xsm.lightsoft.corba.CosTrading.LinkPackage.LimitingFollowTooPermissive value = new hoshen.xsm.lightsoft.corba.CosTrading.LinkPackage.LimitingFollowTooPermissive ();
    // read and discard the repository ID
    istream.read_string ();
    value.limiting_follow_rule = hoshen.xsm.lightsoft.corba.CosTrading.FollowOptionHelper.read (istream);
    value.max_link_follow_policy = hoshen.xsm.lightsoft.corba.CosTrading.FollowOptionHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, hoshen.xsm.lightsoft.corba.CosTrading.LinkPackage.LimitingFollowTooPermissive value)
  {
    // write the repository ID
    ostream.write_string (id ());
    hoshen.xsm.lightsoft.corba.CosTrading.FollowOptionHelper.write (ostream, value.limiting_follow_rule);
    hoshen.xsm.lightsoft.corba.CosTrading.FollowOptionHelper.write (ostream, value.max_link_follow_policy);
  }

}
