package hoshen.xsm.lightsoft.corba.CosTrading.LinkPackage;

/**
* hoshen/xsm/lightsoft/corba/CosTrading/LinkPackage/LinkInfoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from lightsoft/CosTrading.idl
* 13:11:20 GMT+02:00 יום חמישי 28 יוני 2007
*/


/** This structure holds information about federated
 * trader interfaces. It holds references to the Lookup
 * and Register interfaces on the linked trader. Plus
 * policy options about how the link is used.
 */
public final class LinkInfoHolder implements org.omg.CORBA.portable.Streamable
{
  public hoshen.xsm.lightsoft.corba.CosTrading.LinkPackage.LinkInfo value = null;

  public LinkInfoHolder ()
  {
  }

  public LinkInfoHolder (hoshen.xsm.lightsoft.corba.CosTrading.LinkPackage.LinkInfo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = hoshen.xsm.lightsoft.corba.CosTrading.LinkPackage.LinkInfoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    hoshen.xsm.lightsoft.corba.CosTrading.LinkPackage.LinkInfoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return hoshen.xsm.lightsoft.corba.CosTrading.LinkPackage.LinkInfoHelper.type ();
  }

}
