package hoshen.xsm.lightsoft.corba.CosTrading.LookupPackage;


/**
* hoshen/xsm/lightsoft/corba/CosTrading/LookupPackage/SpecifiedPropsHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from lightsoft/CosTrading.idl
* 13:11:19 GMT+02:00 יום חמישי 28 יוני 2007
*/


/** This union is used in a query to determine which
 * properties should be retrieved with returned offers.
 * If some properties are to be retrieved these are
 * specified by name in a property name sequence.
 */
abstract public class SpecifiedPropsHelper
{
  private static String  _id = "IDL:omg.org/CosTrading/Lookup/SpecifiedProps:1.0";

  public static void insert (org.omg.CORBA.Any a, hoshen.xsm.lightsoft.corba.CosTrading.LookupPackage.SpecifiedProps that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static hoshen.xsm.lightsoft.corba.CosTrading.LookupPackage.SpecifiedProps extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      org.omg.CORBA.TypeCode _disTypeCode0;
      _disTypeCode0 = hoshen.xsm.lightsoft.corba.CosTrading.LookupPackage.HowManyPropsHelper.type ();
      org.omg.CORBA.UnionMember[] _members0 = new org.omg.CORBA.UnionMember [3];
      org.omg.CORBA.TypeCode _tcOf_members0;
      org.omg.CORBA.Any _anyOf_members0;

      _anyOf_members0 = org.omg.CORBA.ORB.init ().create_any ();
      // Branch for prop_names (case some)
      hoshen.xsm.lightsoft.corba.CosTrading.LookupPackage.HowManyPropsHelper.insert (_anyOf_members0, hoshen.xsm.lightsoft.corba.CosTrading.LookupPackage.HowManyProps.some);
      _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
      _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (hoshen.xsm.lightsoft.corba.CosTrading.IstringHelper.id (), "Istring", _tcOf_members0);
      _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (hoshen.xsm.lightsoft.corba.CosTrading.PropertyNameHelper.id (), "PropertyName", _tcOf_members0);
      _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
      _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (hoshen.xsm.lightsoft.corba.CosTrading.PropertyNameSeqHelper.id (), "PropertyNameSeq", _tcOf_members0);
      _members0[0] = new org.omg.CORBA.UnionMember (
        "prop_names",
        _anyOf_members0,
        _tcOf_members0,
        null);

      _anyOf_members0 = org.omg.CORBA.ORB.init ().create_any ();
      // Branch for none_dummy (case none)
      hoshen.xsm.lightsoft.corba.CosTrading.LookupPackage.HowManyPropsHelper.insert (_anyOf_members0, hoshen.xsm.lightsoft.corba.CosTrading.LookupPackage.HowManyProps.none);
      _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_short);
      _members0[1] = new org.omg.CORBA.UnionMember (
        "none_dummy",
        _anyOf_members0,
        _tcOf_members0,
        null);

      _anyOf_members0 = org.omg.CORBA.ORB.init ().create_any ();
      // Branch for all_dummy (case all)
      hoshen.xsm.lightsoft.corba.CosTrading.LookupPackage.HowManyPropsHelper.insert (_anyOf_members0, hoshen.xsm.lightsoft.corba.CosTrading.LookupPackage.HowManyProps.all);
      _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_short);
      _members0[2] = new org.omg.CORBA.UnionMember (
        "all_dummy",
        _anyOf_members0,
        _tcOf_members0,
        null);
      __typeCode = org.omg.CORBA.ORB.init ().create_union_tc (hoshen.xsm.lightsoft.corba.CosTrading.LookupPackage.SpecifiedPropsHelper.id (), "SpecifiedProps", _disTypeCode0, _members0);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static hoshen.xsm.lightsoft.corba.CosTrading.LookupPackage.SpecifiedProps read (org.omg.CORBA.portable.InputStream istream)
  {
    hoshen.xsm.lightsoft.corba.CosTrading.LookupPackage.SpecifiedProps value = new hoshen.xsm.lightsoft.corba.CosTrading.LookupPackage.SpecifiedProps ();
    hoshen.xsm.lightsoft.corba.CosTrading.LookupPackage.HowManyProps _dis0 = null;
    _dis0 = hoshen.xsm.lightsoft.corba.CosTrading.LookupPackage.HowManyPropsHelper.read (istream);
    switch (_dis0.value ())
    {
      case hoshen.xsm.lightsoft.corba.CosTrading.LookupPackage.HowManyProps._some:
        String _prop_names[] = null;
        _prop_names = hoshen.xsm.lightsoft.corba.CosTrading.PropertyNameSeqHelper.read (istream);
        value.prop_names (_prop_names);
        break;
      case hoshen.xsm.lightsoft.corba.CosTrading.LookupPackage.HowManyProps._none:
        short _none_dummy = (short)0;
        _none_dummy = istream.read_short ();
        value.none_dummy (_none_dummy);
        break;
      case hoshen.xsm.lightsoft.corba.CosTrading.LookupPackage.HowManyProps._all:
        short _all_dummy = (short)0;
        _all_dummy = istream.read_short ();
        value.all_dummy (_all_dummy);
        break;
      default:
        throw new org.omg.CORBA.BAD_OPERATION ();
    }
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, hoshen.xsm.lightsoft.corba.CosTrading.LookupPackage.SpecifiedProps value)
  {
    hoshen.xsm.lightsoft.corba.CosTrading.LookupPackage.HowManyPropsHelper.write (ostream, value.discriminator ());
    switch (value.discriminator ().value ())
    {
      case hoshen.xsm.lightsoft.corba.CosTrading.LookupPackage.HowManyProps._some:
        hoshen.xsm.lightsoft.corba.CosTrading.PropertyNameSeqHelper.write (ostream, value.prop_names ());
        break;
      case hoshen.xsm.lightsoft.corba.CosTrading.LookupPackage.HowManyProps._none:
        ostream.write_short (value.none_dummy ());
        break;
      case hoshen.xsm.lightsoft.corba.CosTrading.LookupPackage.HowManyProps._all:
        ostream.write_short (value.all_dummy ());
        break;
      default:
    ;
    }
  }

}
