DROP ALIAS USERS;
CREATE ALIAS USERS FOR ODEDN.USERS;
DROP ALIAS USRERS_GROUP;
CREATE ALIAS USERS_GROUP FOR ODEDN.USERS_GROUP;
DROP ALIAS USERS_GROUPS_USERS;
CREATE ALIAS USERS_GROUPS_USERS FOR ODEDN.USERS_GROUPS_USERS;
DROP ALIAS PROPERTIES;
CREATE ALIAS PROPERTIES FOR ODEDN.PROPERTIES;
DROP ALIAS PROJECTS;
CREATE ALIAS PROJECTS FOR ODEDN.PROJECTS;
DROP ALIAS PROJECT_COMPOSITION;
CREATE ALIAS PROJECT_COMPOSITION FOR ODEDN.PROJECT_COMPOSITION;
DROP ALIAS MESSAGES;
CREATE ALIAS MESSAGES FOR ODEDN.MESSAGES;
DROP ALIAS INSTANCES; 
CREATE ALIAS INSTANCES FOR ODEDN.INSTANCES;
DROP ALIAS  GROUPS;
CREATE ALIAS GROUPS FOR ODEDN.GROUPS;
DROP ALIAS ENTITIES_COMPOSITION;
CREATE ALIAS ENTITIES_COMPOSITION FOR ODEDN.ENTITIES_COMPOSITION;
DROP ALIAS ENTITIES;
CREATE ALIAS ENTITIES FOR ODEDN.ENTITIES;
DROP ALIAS DROP ALIAS ;
CREATE ALIAS DOMAINS FOR ODEDN.DOMAINS;
DROP ALIAS DOMAIN_ELEMENTS;
CREATE ALIAS DOMAIN_ELEMENTS FOR ODEDN.DOMAIN_ELEMENTS;
DROP ALIAS ATTRIBUTES;
CREATE ALIAS ATTRIBUTES FOR ODEDN.ATTRIBUTES;




