CONNECT TO DWREPOS;
QUIESCE DATABASE IMMEDIATE FORCE CONNECTIONS;
CONNECT RESET;
BACKUP DATABASE DWREPOS TO "D:\work\" WITH 1 BUFFERS BUFFER 1024 PARALLELISM 1 WITHOUT PROMPTING;
CONNECT TO DWREPOS;
UNQUIESCE DATABASE;
CONNECT RESET;
