#ifndef _OMG_COS_EVENT_COMM_IDL_
#define _OMG_COS_EVENT_COMM_IDL_

//
//	Copyright (c) 1999 IONA Technologies PLC. All Rights Reserved.
//
//   THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF IONA Technologies PLC
//	    The copyright notice above does not evidence any
//	    actual or intended publication of such source code.
//

#pragma IT_SystemSpecification

#pragma IT_BeginCBESpecific AllJava                             "@@\
@module CosEventComm=org.omg"

#pragma prefix "omg.org"

module CosEventComm
{
    exception Disconnected { };

    interface PushConsumer 
    {
        void 
        push(
            in any data
        ) raises (
            Disconnected
        ); 
    
    
        void 
        disconnect_push_consumer ();
    
    };

    interface PushSupplier
    {
        void 
        disconnect_push_supplier();
    
    };

    interface PullSupplier
    {
        any 
        pull(
        ) raises (
            Disconnected
        );
        
        any 
        try_pull(
            out boolean has_event
        ) raises (
            Disconnected
        );

        void 
        disconnect_pull_supplier();
  
    };

    interface PullConsumer
    {
        void 
        disconnect_pull_consumer();

    };

};

#endif  /*!_OMG_COS_EVENT_COMM_IDL_*/
