#ifndef _OMG_COS_TYPED_EVENT_CHANNEL_ADMIN_IDL_
#define _OMG_COS_TYPED_EVENT_CHANNEL_ADMIN_IDL_

//
//	Copyright (c) 1999 IONA Technologies PLC. All Rights Reserved.
//
//   THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF IONA Technologies PLC
//	    The copyright notice above does not evidence any
//	    actual or intended publication of such source code.
//

#pragma IT_SystemSpecification

#include <omg/CosEventChannelAdmin.idl>
#include <omg/CosTypedEventComm.idl>

#pragma prefix "omg.org"

module CosTypedEventChannelAdmin
{

    exception InterfaceNotSupported {};
    exception NoSuchImplementation {};
    typedef string Key;

    interface TypedProxyPushConsumer :
        CosEventChannelAdmin::ProxyPushConsumer,
        CosTypedEventComm::TypedPushConsumer 
    {
    
    };


    interface TypedProxyPullSupplier :
        CosEventChannelAdmin::ProxyPullSupplier,
        CosTypedEventComm::TypedPullSupplier 
    {

    };


    interface TypedSupplierAdmin :
        CosEventChannelAdmin::SupplierAdmin
    {
        TypedProxyPushConsumer 
        obtain_typed_push_consumer(
            in Key supported_interface
        ) raises (
            InterfaceNotSupported
        );

        CosEventChannelAdmin::ProxyPullConsumer 
        obtain_typed_pull_consumer(
            in Key uses_interface
        ) raises (
            NoSuchImplementation
        );

    };

    interface TypedConsumerAdmin :
        CosEventChannelAdmin::ConsumerAdmin
    {
        TypedProxyPullSupplier 
        obtain_typed_pull_supplier(
            in Key supported_interface
        ) raises (
            InterfaceNotSupported
        );

        CosEventChannelAdmin::ProxyPushSupplier 
        obtain_typed_push_supplier(
            in Key uses_interface
        ) raises (
            NoSuchImplementation
        );
        
    };


    interface TypedEventChannel
    {
        TypedConsumerAdmin 
        for_consumers();
    
        TypedSupplierAdmin 
        for_suppliers();
    
        void
        destroy();
    
    };

};

#endif  /*!_OMG_COS_TYPED_EVENT_CHANNEL_ADMIN_IDL_*/
