#ifndef _OMG_DS_NOTIFY_LOG_ADMIN_IDL_
#define _OMG_DS_NOTIFY_LOG_ADMIN_IDL_

//
//	Copyright (c) 1999 IONA Technologies PLC. All Rights Reserved.
//
//   THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF IONA Technologies PLC
//	    The copyright notice above does not evidence any
//	    actual or intended publication of such source code.
//

#include <omg/DsEventLogAdmin.idl>
#include <omg/CosNotifyChannelAdmin.idl>
#include <omg/CosNotifyFilter.idl>
#include <omg/CosNotification.idl>

#pragma IT_SystemSpecification

#pragma prefix "omg.org"

#pragma IT_BeginCBESpecific AllJava                            "@@\
@module DsNotifyLogAdmin=org.omg"
module DsNotifyLogAdmin
{

interface NotifyLog : 
	DsEventLogAdmin::EventLog, CosNotifyChannelAdmin::EventChannel
{
    CosNotifyFilter::Filter get_filter();

    void set_filter(in CosNotifyFilter::Filter filter);
};
    
interface NotifyLogFactory : 
	DsLogAdmin::LogMgr, CosNotifyChannelAdmin::ConsumerAdmin
{
    NotifyLog create (
	in DsLogAdmin::LogFullActionType full_action,
	in unsigned long long max_size,
	in DsLogAdmin::CapacityAlarmThresholdList thresholds,
	in CosNotification::QoSProperties initial_qos,
	in CosNotification::AdminProperties initial_admin,
	out DsLogAdmin::LogId id
	)
	raises (DsLogAdmin::InvalidLogFullAction,
		DsLogAdmin::InvalidThreshold,
		CosNotification::UnsupportedQoS,
		CosNotification::UnsupportedAdmin);
    
    NotifyLog create_with_id (
	in DsLogAdmin::LogId id,
	in DsLogAdmin::LogFullActionType full_action,
	in unsigned long long max_size,
	in DsLogAdmin::CapacityAlarmThresholdList thresholds,
	in CosNotification::QoSProperties initial_qos,
	in CosNotification::AdminProperties initial_admin
	) 
	raises (DsLogAdmin::LogIdAlreadyExists, 
		DsLogAdmin::InvalidLogFullAction,
		DsLogAdmin::InvalidThreshold,
		CosNotification::UnsupportedQoS, 
		CosNotification::UnsupportedAdmin);
};

};

#endif




