#ifndef _OMG_DYNAMIC_IDL_
#define _OMG_DYNAMIC_IDL_

//
//	Copyright (c) 1999 IONA Technologies PLC. All Rights Reserved.
//

// From the Portable Interceptors Submission (99-12-02)
//

#pragma IT_SystemSpecification

#include <omg/orb.idl>

#pragma IT_BeginCBESpecific AllJava                                "@@\
@switch -xLocalityConstrainedInterfaces"

#pragma IT_BeginCBESpecific AllJava                             "@@\
@module Dynamic=org.omg"

#pragma IT_BeginCBESpecific AllJava                                 "@@\
@switch -xHolders -xHelpers"

#pragma prefix "omg.org"

module Dynamic
{
    struct Parameter
    {
	any                  argument;
	CORBA::ParameterMode mode;
    };

    typedef sequence<Parameter>       ParameterList;
    typedef sequence<string>          ContextList;
    typedef sequence<CORBA::TypeCode> ExceptionList;
    typedef CORBA::StringSeq          RequestContext;
};


#endif  /*!_OMG_DYNAMIC_IDL_*/
