#ifndef _OMG_TIMEBASE_IDL_
#define _OMG_TIMEBASE_IDL_

//
//	Copyright (c) 1999 IONA Technologies PLC. All Rights Reserved.
//
//   THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF IONA Technologies PLC
//	    The copyright notice above does not evidence any
//	    actual or intended publication of such source code.
//

#pragma IT_SystemSpecification

#pragma IT_BeginCBESpecific AllJava                                     "@@\
@module TimeBase=org.omg"

#pragma prefix "omg.org"

module TimeBase
{
    typedef unsigned long long TimeT;
    typedef TimeT              InaccuracyT;
    typedef short              TdfT;

    struct UtcT
    {
	TimeT          time;
	unsigned long  inacclo;
	unsigned short inacchi;
	TdfT           tdf;
    };

    struct IntervalT
    {
	TimeT lower_bound;
	TimeT upper_bound;
    };
};


#endif  /*!_OMG_TIMEBASE_IDL_*/
