package hoshen.xsm.lightsoft.corba.CosNotifyFilter;


/**
* hoshen/xsm/lightsoft/corba/CosNotifyFilter/CallbackNotFound.java .
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from lightsoft/CosNotifyFilter.idl
* 13:11:16 GMT+02:00 יום חמישי 28 יוני 2007
*/

public final class CallbackNotFound extends org.omg.CORBA.UserException implements org.omg.CORBA.portable.IDLEntity
{

  public CallbackNotFound ()
  {
    super(CallbackNotFoundHelper.id());
  } // ctor

  public CallbackNotFound (String $reason)
  {
    super(CallbackNotFoundHelper.id() + "  " + $reason);
  } // ctor

} // class CallbackNotFound
