package hoshen.xsm.lightsoft.corba.CosNotifyFilter;


/**
* hoshen/xsm/lightsoft/corba/CosNotifyFilter/InvalidValue.java .
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from lightsoft/CosNotifyFilter.idl
* 13:11:16 GMT+02:00 יום חמישי 28 יוני 2007
*/

public final class InvalidValue extends org.omg.CORBA.UserException implements org.omg.CORBA.portable.IDLEntity
{
  public hoshen.xsm.lightsoft.corba.CosNotifyFilter.ConstraintExp constr = null;
  public org.omg.CORBA.Any value = null;

  public InvalidValue ()
  {
    super(InvalidValueHelper.id());
  } // ctor

  public InvalidValue (hoshen.xsm.lightsoft.corba.CosNotifyFilter.ConstraintExp _constr, org.omg.CORBA.Any _value)
  {
    super(InvalidValueHelper.id());
    constr = _constr;
    value = _value;
  } // Init ctor

  public InvalidValue (String $reason, hoshen.xsm.lightsoft.corba.CosNotifyFilter.ConstraintExp _constr, org.omg.CORBA.Any _value)
  {
    super(InvalidValueHelper.id() + "  " + $reason);
    constr = _constr;
    value = _value;
  } // ctor

} // class InvalidValue
