package hoshen.xsm.lightsoft.corba.CosEventComm;


/**
* hoshen/xsm/lightsoft/corba/CosEventComm/Disconnected.java .
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from lightsoft/CosEventComm.idl
* 13:10:54 GMT+02:00 יום חמישי 28 יוני 2007
*/

public final class Disconnected extends org.omg.CORBA.UserException implements org.omg.CORBA.portable.IDLEntity
{

  public Disconnected ()
  {
    super(DisconnectedHelper.id());
  } // ctor

  public Disconnected (String $reason)
  {
    super(DisconnectedHelper.id() + "  " + $reason);
  } // ctor

} // class Disconnected
