package hoshen.xsm.lightsoft.corba.CosEventComm;


/**
* hoshen/xsm/lightsoft/corba/CosEventComm/PullConsumer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from lightsoft/CosEventComm.idl
* 13:10:54 GMT+02:00 יום חמישי 28 יוני 2007
*/


/**
    * Interface for a pull consumer.
    */
public interface PullConsumer extends PullConsumerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface PullConsumer
