<?xml version="1.0" encoding="UTF-8"?>
<definitions name="OverrideProcessPortTypeJMSBinding"
    targetNamespace="http://override/OverrideProcessPortTypeJMSBinding/"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:format="http://schemas.xmlsoap.org/wsdl/formatbinding/"
    xmlns:interface1="http://override/"
    xmlns:jms="http://schemas.xmlsoap.org/wsdl/jms/"
    xmlns:tns="http://override/OverrideProcessPortTypeJMSBinding/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <import location="OverrideProcessInterface.wsdl" namespace="http://override/"/>
    <binding name="OverrideProcessPortTypeJMSBinding" type="interface1:OverrideProcessPortType">
        <jms:binding type="TextMessage"/>
        <format:typeMapping encoding="XML">
            <format:typeMap formatType="boolean" typeName="xsd:boolean"/>
            <format:typeMap formatType="float" typeName="xsd:float"/>
            <format:typeMap formatType="java.lang.String" typeName="xsd:string"/>
        </format:typeMapping>
        <operation name="InputOperation">
            <jms:operation/>
            <input name="InputOperationRequest">
                <jms:input parts="sum"/>
                <jms:propertyValue name="WSDLBinding" type="xsd:string" value="OverrideProcessPortTypeJMSBinding"/>
                <jms:propertyValue name="WSDLOperation"
                    type="xsd:string" value="InputOperation"/>
            </input>
            <output name="InputOperationResponse">
                <jms:output parts="sum overrideResult chosenManager"/>
            </output>
        </operation>
    </binding>
</definitions>
