<?xml version="1.0" encoding="UTF-8"?>
<definitions name="OverrideProcessPortTypeService"
    targetNamespace="http://override/OverrideProcessPortTypeJMSService/"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:binding1="http://override/OverrideProcessPortTypeJMSBinding/"
    xmlns:jms="http://schemas.xmlsoap.org/wsdl/jms/" xmlns:tns="http://override/OverrideProcessPortTypeJMSService/">
    <import location="OverrideProcessPortTypeJMSBinding.wsdl" namespace="http://override/OverrideProcessPortTypeJMSBinding/"/>
    <service name="OverrideProcessPortTypeService">
        <port binding="binding1:OverrideProcessPortTypeJMSBinding" name="OverrideProcessPortTypeJMSPort">
            <jms:address destinationStyle="queue"
                initialContextFactory="com.ibm.websphere.naming.WsnInitialContextFactory"
                jndiConnectionFactoryName="override/OverrideProcessPortTypeServiceQCF"
                jndiDestinationName="override/OverrideProcessPortTypeServiceQueue" jndiProviderURL="iiop://localhost:2809"/>
        </port>
    </service>
</definitions>
