/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ApplicationProxy */

#ifndef _Included_ApplicationProxy
#define _Included_ApplicationProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ApplicationProxy
 * Method:    printHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ApplicationProxy_printHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
