package hoshen.xsm.lightsoft.corba.CosEventChannelAdmin;


/**
* hoshen/xsm/lightsoft/corba/CosEventChannelAdmin/ProxyPullConsumerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from lightsoft/CosEventChannelAdmin.idl
* 11:11:10 IST יום ראשון 6 נובמבר 2005
*/


/**
    * Interface for a proxy pull consumer.
    */
public interface ProxyPullConsumerOperations  extends hoshen.xsm.lightsoft.corba.CosEventComm.PullConsumerOperations
{

  /**
       * Connect a pull supplier to this proxy.
       * @parm <code>pull_supplier</code> - The <code>PullSupplier</code>
       * object reference.
       * @raises AlreadyConnected If this supplier is already connected.
       * @raises TypeError Illegal supplier type.
       */
  void connect_pull_supplier (hoshen.xsm.lightsoft.corba.CosEventComm.PullSupplier pull_supplier) throws hoshen.xsm.lightsoft.corba.CosEventChannelAdmin.AlreadyConnected, hoshen.xsm.lightsoft.corba.CosEventChannelAdmin.TypeError;
} // interface ProxyPullConsumerOperations
