SET FEEDBACK OFF
SPOOL DATA.TXT

PROMPT DATABASE NAMING DETAILS
SELECT INSTANCE_NAME
FROM   V$INSTANCE;

SELECT GLOBAL_NAME
FROM   GLOBAL_NAME;

PROMPT VERSION DETAILS
SELECT BANNER
FROM V$VERSION
WHERE BANNER LIKE 'Oracle%';

PROMPT BLOCK SIZE DETAILS
select value
from v$parameter
WHERE UPPER(NAME) = 'DB_BLOCK_SIZE';

PROMPT CHARCTER SET DETAILS
SELECT PARAMETER,VALUE
FROM NLS_DATABASE_PARAMETERS
WHERE PARAMETER IN ('NLS_LANGUAGE','NLS_TERRITORY','NLS_CHARACTERSET');

PROMPT DATA FILES DETAILS
SELECT A.TABLESPACE_NAME,A.BLOCKS*B.VALUE/1024 SIZE_KB, A.FILE_NAME
FROM   DBA_DATA_FILES A, V$PARAMETER B
WHERE  UPPER(B.NAME) = 'DB_BLOCK_SIZE'
ORDER BY A.TABLESPACE_NAME,A.FILE_NAME;

PROMPT TABLESPACES DETAILS
SELECT TABLESPACE_NAME,INITIAL_EXTENT,NEXT_EXTENT,MAX_EXTENTS,ALLOCATION_TYPE
FROM DBA_TABLESPACES;

PROMPT ROLLBACK SEGMENTS DETAILS
SELECT SEGMENT_NAME, INITIAL_EXTENT, MIN_EXTENTS, MAX_EXTENTS, PCT_INCREASE, TABLESPACE_NAME
FROM DBA_ROLLBACK_SEGS;

PROMPT REDO LOGS DETAILS
SELECT COUNT(*) NUMBER_OF_FILES, SUM(BYTES)/1024 SIZE_KB
FROM V$LOG;
SPOOL OFF