package hoshen.xsm.lightsoft.corba.equipment;

/**
* hoshen/xsm/lightsoft/corba/equipment/EquipmentHolder_THolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from lightsoft/equipment.idl
* 13:11:34 GMT+02:00 יום חמישי 28 יוני 2007
*/


/**
   * <p>Represents the physical resource of a network element that is 
   * capable of holding other physical resources. Examples of resources 
   * are equipment racks, shelves, or slots.</p>
   * An equipment holder object may contain 
   * a number of instances of other equipment holder objects
   * (for instance representing 
   * slots within a shelf, or shelves within a rack), 
   * and/or a single equipment object.
   *
   * globaldefs::NamingAttributes_T <b>name</b>:
   * <dir>An equipment holder is identified by a unique name.
   * The EMS is responsible for guaranteeing the uniqueness of the name
   * within the context of the ManagedElement.
   * The naming for equipment is deterministic, see
   * <a href=supportingDocumentation/objectNaming.html>Object Naming</a>.
   * </dir>
   *
   * string <b>userLabel</b>:
   * <dir>The userLabel is provisionable by the NMS. This attribute can be set 
   * by the NMS through the Common_I interface service
   * <a href=_common.Common_I.html#common::Common_I::setUserLabel>setUserLabel</a>. 
   * It is a read/write attribute.</dir>
   *
   * string <b>nativeEMSName</b>:
   * <dir> Represents how the equipment holder is referred to on EMS/NE displays. Its
   * aim is to provide a "nomenclature bridge" to aid relating information
   * presented on NMS displays to EMS/NE displays (via GUI cut through).
   * May be a NULL string.</dir>
   *
   * string <b>owner</b>:
   * <dir>owner may be specified by the NMS. May be empty.</dir>
   *
   * boolean <b>alarmReportingIndicator</b>:
   * <dir> Provides an indication whether alarm reporting for this instance 
   * is active or not. It is a read/write attribute.</dir>
   *
   * EquipmentHolderType_T <b>holderType</b>:
   * <dir>Indicates the type of equipment holder.</dir>
   *
   * NamingAttributes_T <b>expectedOrInstalledEquipment</b>: 
   * <dir>The equipment object expected or installed in the equipment holder, if any.
   * NULL if the equipment holder is empty or if it only contains other equipment holders.
   * </dir>
   *
   * EquipmentObjectTypeList_T <b>acceptableEquipmentTypeList</b>: 
   * <dir>Represents the types of equipment objects that can be supported 
   * directly by the equipment holder.  This is an empty list if the equipment holder
   * can only contain other equipment holders.</dir>
   *
   * HolderState_T <b>holderState</b>: 
   * <dir>Represents the state of the equipment holder.</dir>
   *
   * globaldefs::NVSList_T <b>additionalInfo</b>:
   * <dir>This attribute allows the communication from the EMS to the NMS of additional 
   * information which is not explicitly modelled.
   * It is a readonly attribute.</dir>
   **/
public final class EquipmentHolder_THolder implements org.omg.CORBA.portable.Streamable
{
  public hoshen.xsm.lightsoft.corba.equipment.EquipmentHolder_T value = null;

  public EquipmentHolder_THolder ()
  {
  }

  public EquipmentHolder_THolder (hoshen.xsm.lightsoft.corba.equipment.EquipmentHolder_T initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = hoshen.xsm.lightsoft.corba.equipment.EquipmentHolder_THelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    hoshen.xsm.lightsoft.corba.equipment.EquipmentHolder_THelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return hoshen.xsm.lightsoft.corba.equipment.EquipmentHolder_THelper.type ();
  }

}
