<?xml version="1.0" encoding="UTF-8"?>
<definitions name="WSBeanService"
    targetNamespace="http://webservices.wsdl/WSBeanService/"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:binding="http://webservices.wsdl/WSBeanBinding/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://webservices.wsdl/WSBeanService/">
    <import location="WSBeanBinding.wsdl" namespace="http://webservices.wsdl/WSBeanBinding/"/>
    <service name="WSBeanService">
        <port binding="binding:WSBeanBinding" name="WSBeanPort">
            <soap:address location="http://localhost:9080/myweb/servlet/rpcrouter"/>
        </port>
    </service>
</definitions>
