<?xml version="1.0" encoding="UTF-8"?>
<definitions name="WSBeanJava"
    targetNamespace="http://webservices.wsdl/WSBeanJava/"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:format="http://schemas.xmlsoap.org/wsdl/formatbinding/"
    xmlns:interface1="http://webservices.wsdl/WSBean/"
    xmlns:java="http://schemas.xmlsoap.org/wsdl/java/"
    xmlns:tns="http://webservices.wsdl/WSBeanJava/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <import location="WSBean.wsdl" namespace="http://webservices.wsdl/WSBean/"/>
    <binding name="WSBeanJavaBinding" type="interface1:WSBean">
        <java:binding/>
        <format:typeMapping encoding="Java" style="Java">
            <format:typeMap formatType="java.lang.String" typeName="xsd:string"/>
        </format:typeMapping>
        <operation name="getData">
            <java:operation methodName="getData" returnPart="result"/>
            <input name="getDataRequest"/>
            <output name="getDataResponse"/>
        </operation>
        <operation name="setData">
            <java:operation methodName="setData" parameterOrder="data"/>
            <input name="setDataRequest"/>
            <output name="setDataResponse"/>
        </operation>
    </binding>
    <service name="WSBeanService">
        <port binding="tns:WSBeanJavaBinding" name="WSBeanJavaPort">
            <java:address className="webservices.WSBean"/>
        </port>
    </service>
</definitions>
