package hoshen.xsm.lightsoft.corba.CosNaming;


/**
* hoshen/xsm/lightsoft/corba/CosNaming/BindingIteratorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from lightsoft/CosNaming.idl
* 13:10:56 GMT+02:00 יום חמישי 28 יוני 2007
*/


/**
 * The BindingIterator interface allows a client to iterate through the
 * bindings using the next_one or next_n operations.
 */
public interface BindingIteratorOperations 
{

  /**
 * This operation returns the next binding. If there are no more
 * bindings, false is returned.
 *
 * @parm b - next binding.
 */
  boolean next_one (hoshen.xsm.lightsoft.corba.CosNaming.BindingHolder b);

  /** 
 * This operation returns at most the requested number of bindings.
 *
 * @parm how_many - maximum number of binding to return in bl.
 * @parm bl - list of bindings.
 */
  boolean next_n (int how_many, hoshen.xsm.lightsoft.corba.CosNaming.BindingListHolder bl);

  /** 
 * This operation destroys the iterator.
 */
  void destroy ();
} // interface BindingIteratorOperations
