package hoshen.xsm.lightsoft.corba.CosTrading.RegisterPackage;


/**
* hoshen/xsm/lightsoft/corba/CosTrading/RegisterPackage/IllegalTraderName.java .
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from lightsoft/CosTrading.idl
* 13:11:20 GMT+02:00 יום חמישי 28 יוני 2007
*/

public final class IllegalTraderName extends org.omg.CORBA.UserException implements org.omg.CORBA.portable.IDLEntity
{
  public String name[] = null;

  public IllegalTraderName ()
  {
    super(IllegalTraderNameHelper.id());
  } // ctor

  public IllegalTraderName (String[] _name)
  {
    super(IllegalTraderNameHelper.id());
    name = _name;
  } // Init ctor

  public IllegalTraderName (String $reason, String[] _name)
  {
    super(IllegalTraderNameHelper.id() + "  " + $reason);
    name = _name;
  } // ctor

} // class IllegalTraderName
