package hoshen.xsm.lightsoft.corba.CosTrading.RegisterPackage;


/**
* hoshen/xsm/lightsoft/corba/CosTrading/RegisterPackage/InvalidObjectRef.java .
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from lightsoft/CosTrading.idl
* 13:11:20 GMT+02:00 יום חמישי 28 יוני 2007
*/

public final class InvalidObjectRef extends org.omg.CORBA.UserException implements org.omg.CORBA.portable.IDLEntity
{
  public org.omg.CORBA.Object ref = null;

  public InvalidObjectRef ()
  {
    super(InvalidObjectRefHelper.id());
  } // ctor

  public InvalidObjectRef (org.omg.CORBA.Object _ref)
  {
    super(InvalidObjectRefHelper.id());
    ref = _ref;
  } // Init ctor

  public InvalidObjectRef (String $reason, org.omg.CORBA.Object _ref)
  {
    super(InvalidObjectRefHelper.id() + "  " + $reason);
    ref = _ref;
  } // ctor

} // class InvalidObjectRef
