package hoshen.xsm.lightsoft.corba.CosTrading.RegisterPackage;

/**
* hoshen/xsm/lightsoft/corba/CosTrading/RegisterPackage/RegisterNotSupportedHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from lightsoft/CosTrading.idl
* 13:11:20 GMT+02:00 יום חמישי 28 יוני 2007
*/

public final class RegisterNotSupportedHolder implements org.omg.CORBA.portable.Streamable
{
  public hoshen.xsm.lightsoft.corba.CosTrading.RegisterPackage.RegisterNotSupported value = null;

  public RegisterNotSupportedHolder ()
  {
  }

  public RegisterNotSupportedHolder (hoshen.xsm.lightsoft.corba.CosTrading.RegisterPackage.RegisterNotSupported initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = hoshen.xsm.lightsoft.corba.CosTrading.RegisterPackage.RegisterNotSupportedHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    hoshen.xsm.lightsoft.corba.CosTrading.RegisterPackage.RegisterNotSupportedHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return hoshen.xsm.lightsoft.corba.CosTrading.RegisterPackage.RegisterNotSupportedHelper.type ();
  }

}
