package hoshen.xsm.lightsoft.corba.CosEventChannelAdmin;


/**
* hoshen/xsm/lightsoft/corba/CosEventChannelAdmin/ProxyPullConsumer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from lightsoft/CosEventChannelAdmin.idl
* 13:10:53 GMT+02:00 יום חמישי 28 יוני 2007
*/


/**
    * Interface for a proxy pull consumer.
    */
public interface ProxyPullConsumer extends ProxyPullConsumerOperations, hoshen.xsm.lightsoft.corba.CosEventComm.PullConsumer, org.omg.CORBA.portable.IDLEntity 
{
} // interface ProxyPullConsumer
