package hoshen.xsm.lightsoft.corba.CosEventChannelAdmin;


/**
* hoshen/xsm/lightsoft/corba/CosEventChannelAdmin/SupplierAdminOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from lightsoft/CosEventChannelAdmin.idl
* 13:10:53 GMT+02:00 יום חמישי 28 יוני 2007
*/


/**
    * Interface for the supplier administration object.
    */
public interface SupplierAdminOperations 
{

  /**
       * Obtain a push consumer proxy for this administration object.
       * @returns A <code>ProxyPushConsumer</code> object reference.
       */
  hoshen.xsm.lightsoft.corba.CosEventChannelAdmin.ProxyPushConsumer obtain_push_consumer ();

  /**
       * Obtain a pull consumer proxy for this administration object.
       * @returns A <code>ProxyPullConsumer</code> object reference.
       */
  hoshen.xsm.lightsoft.corba.CosEventChannelAdmin.ProxyPullConsumer obtain_pull_consumer ();
} // interface SupplierAdminOperations
