DROP TABLE GLST_SAMCHUT_MNHL
CREATE TABLE GLST_SAMCHUT_MNHL (
GK_SAMCHUT_MNHL tinyint NOT NULL,
GK_SMACHUT_MNHL_OT char(1)
);
ALTER TABLE GLST_SAMCHUT_MNHL ADD CONSTRAINT GLST_SMACHUT_MNHL_PK PRIMARY KEY (GK_SAMCHUT_MNHL);

insert into GLST_SAMCHUT_MNHL values (0, ' ');
insert into GLST_SAMCHUT_MNHL values (1, 'à');