DROP TABLE GLST_TESHUVA;
CREATE TABLE GLST_TESHUVA (
GL_KOD_TESHUVA tinyint NOT NULL,
GL_TEUR_TESHUVA_OT varchar(15)
);
ALTER TABLE GLST_TESHUVA ADD CONSTRAINT GLST_TESHUVA_PK PRIMARY KEY (GL_KOD_TESHUVA);

