DROP TABLE REFTABLES_CTL;
CREATE TABLE REFTABLES_CTL( 
	TABLE_NAME VARCHAR(40) NOT NULL, 
	TS DATETIME);
ALTER TABLE REFTABLES_CTL ADD CONSTRAINT  REFTABLES_CTL_PK PRIMARY KEY (TABLE_NAME);
CREATE INDEX REFTABLES_CTL_INX ON REFTABLES_CTL(TABLE_NAME);