#ifndef notifications_idl
#define notifications_idl

// ********************************
// *                              *
// * notifications.idl            *
// *                              *
// ********************************

//Include list
#include "globaldefs.idl"
#include "CosNotification.idl"

#pragma prefix "mtnm.tmforum.org"

  /** 
   * <a href=supportingDocumentation/overview.html>Overview of NML-EML interface</a>
   *
   * <p>This module contains the definition of the notification portions
   * of the NML-EML interface. See
   * <a href=supportingDocumentation/notificationServiceUsage.html>Notification Service Usage</a>
   * for details on how this interface uses the notification service.</p>
   *
   * <h5> Version 2.0. </h5>
   **/


module notifications
{
  /**
   * <p>ObjectType is an attribute of all notifications.
   * The enum avoids any uncertainty in the type of object and allows
   * simple filtering.</p>
   *
   * <p>A notification must be reported against the correct object if it
   * is modelled.</p> 
   *
   * <p>For alarms, the objectType OT_AID is used to represent the EMS 
   * object types that are not modelled.  Other notifications types
   * should not be reported against AIDs.</p>
   **/
   enum  ObjectType_T
   {
     OT_EMS,
     OT_MANAGED_ELEMENT,
     OT_MULTILAYER_SUBNETWORK,
     OT_TOPOLOGICAL_LINK,
     OT_SUBNETWORK_CONNECTION,
     OT_PHYSICAL_TERMINATION_POINT,
     OT_CONNECTION_TERMINATION_POINT,
     OT_TERMINATION_POINT_POOL,
     OT_EQUIPMENT_HOLDER,
     OT_EQUIPMENT,
     OT_PROTECTION_GROUP,
     OT_TRAFFIC_DESCRIPTOR,
     OT_AID
   };


  /**
   * <p>The PerceivedSeverity_T values are consistent
   * with ITU-T X.733 definitions.<p>
   * 
   **/
   enum  PerceivedSeverity_T
   {
     PS_INDETERMINATE,
     PS_CRITICAL,
     PS_MAJOR,
     PS_MINOR,
     PS_WARNING,
     PS_CLEARED
   };


  /**
   * <p>List of PerceivedSeverity_T values.<p>
   * 
   **/
   typedef sequence<PerceivedSeverity_T> PerceivedSeverityList_T;


  /**
   * <p>ServiceAffecting_T describes the impact of a fault on monitored entities</p>
   * <dir>SA_UNKNOWN: The EMS cannot determine if the condition 
   *  affects service or not.</dir>
   * <dir>SA_SERVICE_AFFECTING: The EMS determines the condition affects service.</dir>
   * <dir>SA_NON_SERVICE_AFFECTING: The EMS determines the condition does not
   *  affect service.</dir>
   **/
   enum ServiceAffecting_T
   {
    SA_UNKNOWN,
    SA_SERVICE_AFFECTING,
    SA_NON_SERVICE_AFFECTING
   };
 

  /**
   * <p>Set of probable causes.  
   * See <a href=supportingDocumentation/notificationServiceUsage.html> Notification
   * Service Usage</a> for a description of the probable cause strings.</p>
   **/
  typedef sequence<string> ProbableCauseList_T;


  /**
   * <p>The NameAndAnyValue_T structure is provided when an any value is needed.</p>
   **/
   struct NameAndAnyValue_T
   {
     string      name;
     any         value;
   };


  /**
   * <p>A list of (name=string, value=any) tuples. The OMG standard 
   * NVList.  This is used for AttributeValueChange and StateChange notifications (see
   * <a href=supportingDocumentation/notificationServiceUsage.html> Notification
   * Service Usage</a>.</p>
   **/
   typedef sequence<NameAndAnyValue_T> NVList_T;


  /**
   * Describe transfer status type.  This is used for FTP notifications (see
   * <a href=supportingDocumentation/notificationServiceUsage.html> Notification
   * Service Usage</a>.</p>
   */
  enum FileTransferStatus_T
  {
    FT_IN_PROGRESS,
    FT_FAILED,
    FT_COMPLETED
  };

  
  /**
   * <p>Sequence of CosNotification::StructuredEvent</p>
   **/
  typedef sequence<CosNotification::StructuredEvent> EventList_T;


  /**
   * <p>In order to allow the NMS to deal with a large number of objects,
   * iterators are used.</p>
   * <p>See <a href=supportingDocumentation/iterators.html>iterator overview</a>
   * for information on how iterators are used in this interface.</p>
   **/
   interface EventIterator_I 
    {
	boolean  next_n(in unsigned long how_many,
		        out EventList_T eventList)
	         raises (globaldefs::ProcessingFailureException);

        unsigned long getLength()
	         raises (globaldefs::ProcessingFailureException);

   	void	 destroy()
	         raises (globaldefs::ProcessingFailureException);
    };


};

#endif

