package hoshen.xsm.lightsoft.corba.CosNaming.NamingContextPackage;


/**
* hoshen/xsm/lightsoft/corba/CosNaming/NamingContextPackage/CannotProceed.java .
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from lightsoft/CosNaming.idl
* 13:10:56 GMT+02:00 יום חמישי 28 יוני 2007
*/

public final class CannotProceed extends org.omg.CORBA.UserException implements org.omg.CORBA.portable.IDLEntity
{
  public hoshen.xsm.lightsoft.corba.CosNaming.NamingContext cxt = null;
  public hoshen.xsm.lightsoft.corba.CosNaming.NameComponent rest_of_name[] = null;

  public CannotProceed ()
  {
    super(CannotProceedHelper.id());
  } // ctor

  public CannotProceed (hoshen.xsm.lightsoft.corba.CosNaming.NamingContext _cxt, hoshen.xsm.lightsoft.corba.CosNaming.NameComponent[] _rest_of_name)
  {
    super(CannotProceedHelper.id());
    cxt = _cxt;
    rest_of_name = _rest_of_name;
  } // Init ctor

  public CannotProceed (String $reason, hoshen.xsm.lightsoft.corba.CosNaming.NamingContext _cxt, hoshen.xsm.lightsoft.corba.CosNaming.NameComponent[] _rest_of_name)
  {
    super(CannotProceedHelper.id() + "  " + $reason);
    cxt = _cxt;
    rest_of_name = _rest_of_name;
  } // ctor

} // class CannotProceed
