package hoshen.xsm.lightsoft.corba.CosNaming.NamingContextPackage;


/**
* hoshen/xsm/lightsoft/corba/CosNaming/NamingContextPackage/NotFound.java .
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from lightsoft/CosNaming.idl
* 13:10:56 GMT+02:00 יום חמישי 28 יוני 2007
*/

public final class NotFound extends org.omg.CORBA.UserException implements org.omg.CORBA.portable.IDLEntity
{
  public hoshen.xsm.lightsoft.corba.CosNaming.NamingContextPackage.NotFoundReason why = null;
  public hoshen.xsm.lightsoft.corba.CosNaming.NameComponent rest_of_name[] = null;

  public NotFound ()
  {
    super(NotFoundHelper.id());
  } // ctor

  public NotFound (hoshen.xsm.lightsoft.corba.CosNaming.NamingContextPackage.NotFoundReason _why, hoshen.xsm.lightsoft.corba.CosNaming.NameComponent[] _rest_of_name)
  {
    super(NotFoundHelper.id());
    why = _why;
    rest_of_name = _rest_of_name;
  } // Init ctor

  public NotFound (String $reason, hoshen.xsm.lightsoft.corba.CosNaming.NamingContextPackage.NotFoundReason _why, hoshen.xsm.lightsoft.corba.CosNaming.NameComponent[] _rest_of_name)
  {
    super(NotFoundHelper.id() + "  " + $reason);
    why = _why;
    rest_of_name = _rest_of_name;
  } // ctor

} // class NotFound
