package hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin;


/**
* hoshen/xsm/lightsoft/corba/CosNotifyChannelAdmin/AdminLimit.java .
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from lightsoft/CosNotifyChannelAdmin.idl
* 13:11:07 GMT+02:00 יום חמישי 28 יוני 2007
*/


/**
    * Structure used for <code>AdminLimitExceeded</code> exceptions.
    * It is a two-tuple of a property name and a property value.
    */
public final class AdminLimit implements org.omg.CORBA.portable.IDLEntity
{
  public String name = "";
  public org.omg.CORBA.Any value = null;

  public AdminLimit ()
  {
  } // ctor

  public AdminLimit (String _name, org.omg.CORBA.Any _value)
  {
    name = _name;
    value = _value;
  } // Init ctor

} // class AdminLimit
