package hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin;


/**
* hoshen/xsm/lightsoft/corba/CosNotifyChannelAdmin/ClientType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from lightsoft/CosNotifyChannelAdmin.idl
* 13:11:07 GMT+02:00 יום חמישי 28 יוני 2007
*/


/**
    * Enumeration of client types.
    */
public class ClientType implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 3;
  private static hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin.ClientType[] __array = new hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin.ClientType [__size];

  public static final int _ANY_EVENT = 0;
  public static final hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin.ClientType ANY_EVENT = new hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin.ClientType(_ANY_EVENT);
  public static final int _STRUCTURED_EVENT = 1;
  public static final hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin.ClientType STRUCTURED_EVENT = new hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin.ClientType(_STRUCTURED_EVENT);
  public static final int _SEQUENCE_EVENT = 2;
  public static final hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin.ClientType SEQUENCE_EVENT = new hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin.ClientType(_SEQUENCE_EVENT);

  public int value ()
  {
    return __value;
  }

  public static hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin.ClientType from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected ClientType (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class ClientType
