package hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin;


/**
* hoshen/xsm/lightsoft/corba/CosNotifyChannelAdmin/ConsumerAdminOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from lightsoft/CosNotifyChannelAdmin.idl
* 13:11:07 GMT+02:00 יום חמישי 28 יוני 2007
*/


/**
    * An interface for consumer administration objects.
    */
public interface ConsumerAdminOperations  extends hoshen.xsm.lightsoft.corba.CosNotification.QoSAdminOperations, hoshen.xsm.lightsoft.corba.CosNotifyComm.NotifySubscribeOperations, hoshen.xsm.lightsoft.corba.CosNotifyFilter.FilterAdminOperations, hoshen.xsm.lightsoft.corba.CosEventChannelAdmin.ConsumerAdminOperations
{

  /**
       * A unique identifier for this administration object.
       */
  int MyID ();

  /**
       * The event channel object that created this administration object.
       */
  hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin.EventChannel MyChannel ();

  /**
       * Indicates whether AND or OR semantics is used when combining 
       * administration object filters and proxy filters.
       */
  hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin.InterFilterGroupOperator MyOperator ();

  /**
       * A mapping filter which if a non-nil reference will be consulted 
       * for resolving the priority of the event.
       */
  hoshen.xsm.lightsoft.corba.CosNotifyFilter.MappingFilter priority_filter ();

  /**
       * A mapping filter which if a non-nil reference will be consulted 
       * for resolving the priority of the event.
       */
  void priority_filter (hoshen.xsm.lightsoft.corba.CosNotifyFilter.MappingFilter newPriority_filter);

  /**
       * A mapping filter which if a non-nil reference will be consulted 
       * for resolving the lifetime of the event.
       */
  hoshen.xsm.lightsoft.corba.CosNotifyFilter.MappingFilter lifetime_filter ();

  /**
       * A mapping filter which if a non-nil reference will be consulted 
       * for resolving the lifetime of the event.
       */
  void lifetime_filter (hoshen.xsm.lightsoft.corba.CosNotifyFilter.MappingFilter newLifetime_filter);

  /**
       * A list of pull supplier proxies created by the administration object.
       */
  int[] pull_suppliers ();

  /**
       * A list of push supplier proxies created by the administration object.
       */
  int[] push_suppliers ();

  /**
       * Get the proxy with the specified ID.
       * @parm <code>proxy_id</code> - The ID of the proxy to retrieve.
       * @raises ProxyNotFound If no proxy with the specified ID could 
       * be found.
       */
  hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin.ProxySupplier get_proxy_supplier (int proxy_id) throws hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin.ProxyNotFound;

  /**
       * Obtain a pull supplier proxy for this administration object.
       * @parm <code>ctype</code> - The client type.
       * @parm <code>proxy_id</code> - The ID of the newly created proxy,
       * i.e. the return value.
       * @returns A ProxySupplier object reference.
       * @raises AdminLimitExceeded If the number of proxies associated 
       * with this administration object exceeds the MaxConsumers property.
       */
  hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin.ProxySupplier obtain_notification_pull_supplier (hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin.ClientType ctype, org.omg.CORBA.IntHolder proxy_id) throws hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin.AdminLimitExceeded;

  /**
       * Obtain a push supplier proxy for this administration object.
       * @parm <code>ctype</code> - The client type.
       * @parm <code>proxy_id</code> - The ID of the newly created proxy,
       * i.e. the return value.
       * @returns A ProxySupplier object reference.
       * @raises AdminLimitExceeded If the number of proxies associated 
       * with this administration object exceeds the MaxConsumers property.
       */
  hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin.ProxySupplier obtain_notification_push_supplier (hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin.ClientType ctype, org.omg.CORBA.IntHolder proxy_id) throws hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin.AdminLimitExceeded;

  /**
       * Destroy this administration object and all proxies created by it.
       */
  void destroy ();
} // interface ConsumerAdminOperations
