package hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin;


/**
* hoshen/xsm/lightsoft/corba/CosNotifyChannelAdmin/ConsumerAdminPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from lightsoft/CosNotifyChannelAdmin.idl
* 13:11:07 GMT+02:00 יום חמישי 28 יוני 2007
*/


/**
    * An interface for consumer administration objects.
    */
public abstract class ConsumerAdminPOA extends org.omg.PortableServer.Servant
                implements hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin.ConsumerAdminOperations, org.omg.CORBA.portable.InvokeHandler
{

  public hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin.ConsumerAdmin _this() {
     return hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin.ConsumerAdminHelper.narrow(
        super._this_object());
  }

  public hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin.ConsumerAdmin _this(org.omg.CORBA.ORB orb) {
     return hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin.ConsumerAdminHelper.narrow(
        super._this_object(orb));
  }

  public String[] _all_interfaces(
     org.omg.PortableServer.POA poa,
     byte[] objectId) {
         return (String[])__ids.clone();
  }

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:omg.org/CosNotifyChannelAdmin/ConsumerAdmin:1.0", 
    "IDL:omg.org/CosNotification/QoSAdmin:1.0", 
    "IDL:omg.org/CosNotifyComm/NotifySubscribe:1.0", 
    "IDL:omg.org/CosNotifyFilter/FilterAdmin:1.0", 
    "IDL:omg.org/CosEventChannelAdmin/ConsumerAdmin:1.0"};

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_MyID", new java.lang.Integer (0));
    _methods.put ("_get_MyChannel", new java.lang.Integer (1));
    _methods.put ("_get_MyOperator", new java.lang.Integer (2));
    _methods.put ("_get_priority_filter", new java.lang.Integer (3));
    _methods.put ("_set_priority_filter", new java.lang.Integer (4));
    _methods.put ("_get_lifetime_filter", new java.lang.Integer (5));
    _methods.put ("_set_lifetime_filter", new java.lang.Integer (6));
    _methods.put ("_get_pull_suppliers", new java.lang.Integer (7));
    _methods.put ("_get_push_suppliers", new java.lang.Integer (8));
    _methods.put ("get_proxy_supplier", new java.lang.Integer (9));
    _methods.put ("obtain_notification_pull_supplier", new java.lang.Integer (10));
    _methods.put ("obtain_notification_push_supplier", new java.lang.Integer (11));
    _methods.put ("destroy", new java.lang.Integer (12));
    _methods.put ("get_qos", new java.lang.Integer (13));
    _methods.put ("set_qos", new java.lang.Integer (14));
    _methods.put ("validate_qos", new java.lang.Integer (15));
    _methods.put ("subscription_change", new java.lang.Integer (16));
    _methods.put ("add_filter", new java.lang.Integer (17));
    _methods.put ("remove_filter", new java.lang.Integer (18));
    _methods.put ("get_filter", new java.lang.Integer (19));
    _methods.put ("get_all_filters", new java.lang.Integer (20));
    _methods.put ("remove_all_filters", new java.lang.Integer (21));
    _methods.put ("obtain_push_supplier", new java.lang.Integer (22));
    _methods.put ("obtain_pull_supplier", new java.lang.Integer (23));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  /**
       * A unique identifier for this administration object.
       */
       case 0:  // CosNotifyChannelAdmin/ConsumerAdmin/_get_MyID
       {
         int __result = (int)0;
         __result = this.MyID ();
         out = $rh.createReply();
         out.write_long (__result);
         break;
       }


  /**
       * The event channel object that created this administration object.
       */
       case 1:  // CosNotifyChannelAdmin/ConsumerAdmin/_get_MyChannel
       {
         hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin.EventChannel __result = null;
         __result = this.MyChannel ();
         out = $rh.createReply();
         hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin.EventChannelHelper.write (out, __result);
         break;
       }


  /**
       * Indicates whether AND or OR semantics is used when combining 
       * administration object filters and proxy filters.
       */
       case 2:  // CosNotifyChannelAdmin/ConsumerAdmin/_get_MyOperator
       {
         hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin.InterFilterGroupOperator __result = null;
         __result = this.MyOperator ();
         out = $rh.createReply();
         hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin.InterFilterGroupOperatorHelper.write (out, __result);
         break;
       }


  /**
       * A mapping filter which if a non-nil reference will be consulted 
       * for resolving the priority of the event.
       */
       case 3:  // CosNotifyChannelAdmin/ConsumerAdmin/_get_priority_filter
       {
         hoshen.xsm.lightsoft.corba.CosNotifyFilter.MappingFilter __result = null;
         __result = this.priority_filter ();
         out = $rh.createReply();
         hoshen.xsm.lightsoft.corba.CosNotifyFilter.MappingFilterHelper.write (out, __result);
         break;
       }


  /**
       * A mapping filter which if a non-nil reference will be consulted 
       * for resolving the priority of the event.
       */
       case 4:  // CosNotifyChannelAdmin/ConsumerAdmin/_set_priority_filter
       {
         hoshen.xsm.lightsoft.corba.CosNotifyFilter.MappingFilter newPriority_filter = hoshen.xsm.lightsoft.corba.CosNotifyFilter.MappingFilterHelper.read (in);
         this.priority_filter (newPriority_filter);
         out = $rh.createReply();
         break;
       }


  /**
       * A mapping filter which if a non-nil reference will be consulted 
       * for resolving the lifetime of the event.
       */
       case 5:  // CosNotifyChannelAdmin/ConsumerAdmin/_get_lifetime_filter
       {
         hoshen.xsm.lightsoft.corba.CosNotifyFilter.MappingFilter __result = null;
         __result = this.lifetime_filter ();
         out = $rh.createReply();
         hoshen.xsm.lightsoft.corba.CosNotifyFilter.MappingFilterHelper.write (out, __result);
         break;
       }


  /**
       * A mapping filter which if a non-nil reference will be consulted 
       * for resolving the lifetime of the event.
       */
       case 6:  // CosNotifyChannelAdmin/ConsumerAdmin/_set_lifetime_filter
       {
         hoshen.xsm.lightsoft.corba.CosNotifyFilter.MappingFilter newLifetime_filter = hoshen.xsm.lightsoft.corba.CosNotifyFilter.MappingFilterHelper.read (in);
         this.lifetime_filter (newLifetime_filter);
         out = $rh.createReply();
         break;
       }


  /**
       * A list of pull supplier proxies created by the administration object.
       */
       case 7:  // CosNotifyChannelAdmin/ConsumerAdmin/_get_pull_suppliers
       {
         int __result[] = null;
         __result = this.pull_suppliers ();
         out = $rh.createReply();
         hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin.ProxyIDSeqHelper.write (out, __result);
         break;
       }


  /**
       * A list of push supplier proxies created by the administration object.
       */
       case 8:  // CosNotifyChannelAdmin/ConsumerAdmin/_get_push_suppliers
       {
         int __result[] = null;
         __result = this.push_suppliers ();
         out = $rh.createReply();
         hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin.ProxyIDSeqHelper.write (out, __result);
         break;
       }


  /**
       * Get the proxy with the specified ID.
       * @parm <code>proxy_id</code> - The ID of the proxy to retrieve.
       * @raises ProxyNotFound If no proxy with the specified ID could 
       * be found.
       */
       case 9:  // CosNotifyChannelAdmin/ConsumerAdmin/get_proxy_supplier
       {
         try {
           int proxy_id = in.read_long ();
           hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin.ProxySupplier __result = null;
           __result = this.get_proxy_supplier (proxy_id);
           out = $rh.createReply();
           hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin.ProxySupplierHelper.write (out, __result);
         } catch (hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin.ProxyNotFound __ex) {
           out = $rh.createExceptionReply ();
           hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin.ProxyNotFoundHelper.write (out, __ex);
         }
         break;
       }


  /**
       * Obtain a pull supplier proxy for this administration object.
       * @parm <code>ctype</code> - The client type.
       * @parm <code>proxy_id</code> - The ID of the newly created proxy,
       * i.e. the return value.
       * @returns A ProxySupplier object reference.
       * @raises AdminLimitExceeded If the number of proxies associated 
       * with this administration object exceeds the MaxConsumers property.
       */
       case 10:  // CosNotifyChannelAdmin/ConsumerAdmin/obtain_notification_pull_supplier
       {
         try {
           hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin.ClientType ctype = hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin.ClientTypeHelper.read (in);
           org.omg.CORBA.IntHolder proxy_id = new org.omg.CORBA.IntHolder ();
           hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin.ProxySupplier __result = null;
           __result = this.obtain_notification_pull_supplier (ctype, proxy_id);
           out = $rh.createReply();
           hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin.ProxySupplierHelper.write (out, __result);
           out.write_long (proxy_id.value);
         } catch (hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin.AdminLimitExceeded __ex) {
           out = $rh.createExceptionReply ();
           hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin.AdminLimitExceededHelper.write (out, __ex);
         }
         break;
       }


  /**
       * Obtain a push supplier proxy for this administration object.
       * @parm <code>ctype</code> - The client type.
       * @parm <code>proxy_id</code> - The ID of the newly created proxy,
       * i.e. the return value.
       * @returns A ProxySupplier object reference.
       * @raises AdminLimitExceeded If the number of proxies associated 
       * with this administration object exceeds the MaxConsumers property.
       */
       case 11:  // CosNotifyChannelAdmin/ConsumerAdmin/obtain_notification_push_supplier
       {
         try {
           hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin.ClientType ctype = hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin.ClientTypeHelper.read (in);
           org.omg.CORBA.IntHolder proxy_id = new org.omg.CORBA.IntHolder ();
           hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin.ProxySupplier __result = null;
           __result = this.obtain_notification_push_supplier (ctype, proxy_id);
           out = $rh.createReply();
           hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin.ProxySupplierHelper.write (out, __result);
           out.write_long (proxy_id.value);
         } catch (hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin.AdminLimitExceeded __ex) {
           out = $rh.createExceptionReply ();
           hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin.AdminLimitExceededHelper.write (out, __ex);
         }
         break;
       }


  /**
       * Destroy this administration object and all proxies created by it.
       */
       case 12:  // CosNotifyChannelAdmin/ConsumerAdmin/destroy
       {
         this.destroy ();
         out = $rh.createReply();
         break;
       }


  /**
       * Returns the current quality of service settings for this object.
       * @returns A sequence of name-value pairs defining the quality of 
       * service settings.
       */
       case 13:  // CosNotification/QoSAdmin/get_qos
       {
         hoshen.xsm.lightsoft.corba.CosNotification.Property __result[] = null;
         __result = this.get_qos ();
         out = $rh.createReply();
         hoshen.xsm.lightsoft.corba.CosNotification.PropertySeqHelper.write (out, __result);
         break;
       }


  /**
       * Sets the quality of service settings for this object.
       * @parm <code>qos</code> - A sequence of name-value pairs defining
       * the desired quality of service settings.
       * @raises UnsupportedQoS If the requested settings are not supported.
       */
       case 14:  // CosNotification/QoSAdmin/set_qos
       {
         try {
           hoshen.xsm.lightsoft.corba.CosNotification.Property qos[] = hoshen.xsm.lightsoft.corba.CosNotification.PropertySeqHelper.read (in);
           this.set_qos (qos);
           out = $rh.createReply();
         } catch (hoshen.xsm.lightsoft.corba.CosNotification.UnsupportedQoS __ex) {
           out = $rh.createExceptionReply ();
           hoshen.xsm.lightsoft.corba.CosNotification.UnsupportedQoSHelper.write (out, __ex);
         }
         break;
       }


  /**
       * Validates a set of quality of service requirements.
       * @parm <code>qos</code> -  A sequence of name-value pairs defining
       * quality of service settings that are to be validated.
       * @parm <code>available_qos</code> - A sequence of all additional
       * quality of service setting supported by this object.
       * @raises UnsupportedQoS If any of the setting in the input argument
       * are not supported.
       */
       case 15:  // CosNotification/QoSAdmin/validate_qos
       {
         try {
           hoshen.xsm.lightsoft.corba.CosNotification.Property required_qos[] = hoshen.xsm.lightsoft.corba.CosNotification.PropertySeqHelper.read (in);
           hoshen.xsm.lightsoft.corba.CosNotification.NamedPropertyRangeSeqHolder available_qos = new hoshen.xsm.lightsoft.corba.CosNotification.NamedPropertyRangeSeqHolder ();
           this.validate_qos (required_qos, available_qos);
           out = $rh.createReply();
           hoshen.xsm.lightsoft.corba.CosNotification.NamedPropertyRangeSeqHelper.write (out, available_qos.value);
         } catch (hoshen.xsm.lightsoft.corba.CosNotification.UnsupportedQoS __ex) {
           out = $rh.createExceptionReply ();
           hoshen.xsm.lightsoft.corba.CosNotification.UnsupportedQoSHelper.write (out, __ex);
         }
         break;
       }


  /**
       * Indicates that a consumer is changing the names of the types of
       * events it is subscribed to.
       * @parm <code>added</code> - The event types added.
       * @parm <code>removed</code> - The event types removed.
       * @raises InvalidEventType If any of the event type names in either 
       * the of the input sequences are invalid.
       */
       case 16:  // CosNotifyComm/NotifySubscribe/subscription_change
       {
         try {
           hoshen.xsm.lightsoft.corba.CosNotification.EventType added[] = hoshen.xsm.lightsoft.corba.CosNotification.EventTypeSeqHelper.read (in);
           hoshen.xsm.lightsoft.corba.CosNotification.EventType removed[] = hoshen.xsm.lightsoft.corba.CosNotification.EventTypeSeqHelper.read (in);
           this.subscription_change (added, removed);
           out = $rh.createReply();
         } catch (hoshen.xsm.lightsoft.corba.CosNotifyComm.InvalidEventType __ex) {
           out = $rh.createExceptionReply ();
           hoshen.xsm.lightsoft.corba.CosNotifyComm.InvalidEventTypeHelper.write (out, __ex);
         }
         break;
       }


  /**
       * Add a filter to this object's list of filters. All these filters
       * are tried upon reception of an event.
       * @parm <code>new_filter</code> - The filter to add.
       * @returns An unique ID that identifies the added filter.
       */
       case 17:  // CosNotifyFilter/FilterAdmin/add_filter
       {
         hoshen.xsm.lightsoft.corba.CosNotifyFilter.Filter new_filter = hoshen.xsm.lightsoft.corba.CosNotifyFilter.FilterHelper.read (in);
         int __result = (int)0;
         __result = this.add_filter (new_filter);
         out = $rh.createReply();
         out.write_long (__result);
         break;
       }


  /**
       * Remove a filter from this object's list of filters.
       * @parm <code>filter</code> - The filter ID.
       * @raises FilterNotFound If the ID does not correspond to any
       * filter that has been added to this object.
       */
       case 18:  // CosNotifyFilter/FilterAdmin/remove_filter
       {
         try {
           int filter = in.read_long ();
           this.remove_filter (filter);
           out = $rh.createReply();
         } catch (hoshen.xsm.lightsoft.corba.CosNotifyFilter.FilterNotFound __ex) {
           out = $rh.createExceptionReply ();
           hoshen.xsm.lightsoft.corba.CosNotifyFilter.FilterNotFoundHelper.write (out, __ex);
         }
         break;
       }


  /**
       * Get a filter from the filter ID.
       * @parm <code>filter</code> - The filter ID.
       * @raises FilterNotFound If the ID does not correspond to any
       * filter that has been added to this object.
       */
       case 19:  // CosNotifyFilter/FilterAdmin/get_filter
       {
         try {
           int filter = in.read_long ();
           hoshen.xsm.lightsoft.corba.CosNotifyFilter.Filter __result = null;
           __result = this.get_filter (filter);
           out = $rh.createReply();
           hoshen.xsm.lightsoft.corba.CosNotifyFilter.FilterHelper.write (out, __result);
         } catch (hoshen.xsm.lightsoft.corba.CosNotifyFilter.FilterNotFound __ex) {
           out = $rh.createExceptionReply ();
           hoshen.xsm.lightsoft.corba.CosNotifyFilter.FilterNotFoundHelper.write (out, __ex);
         }
         break;
       }


  /**
       * Get all filters added to this administration object.
       * @returns A sequence of filter IDs.
       */
       case 20:  // CosNotifyFilter/FilterAdmin/get_all_filters
       {
         int __result[] = null;
         __result = this.get_all_filters ();
         out = $rh.createReply();
         hoshen.xsm.lightsoft.corba.CosNotifyFilter.FilterIDSeqHelper.write (out, __result);
         break;
       }


  /**
       * Remove all filters added to this administration object.
       */
       case 21:  // CosNotifyFilter/FilterAdmin/remove_all_filters
       {
         this.remove_all_filters ();
         out = $rh.createReply();
         break;
       }


  /**
       * Obtain a push supplier proxy for this administration object.
       * @returns A <code>ProxyPushSupplier</code> object reference.
       */
       case 22:  // CosEventChannelAdmin/ConsumerAdmin/obtain_push_supplier
       {
         hoshen.xsm.lightsoft.corba.CosEventChannelAdmin.ProxyPushSupplier __result = null;
         __result = this.obtain_push_supplier ();
         out = $rh.createReply();
         hoshen.xsm.lightsoft.corba.CosEventChannelAdmin.ProxyPushSupplierHelper.write (out, __result);
         break;
       }


  /**
       * Obtain a pull supplier proxy for this administration object.
       * @returns A <code>ProxyPullSupplier</code> object reference.
       */
       case 23:  // CosEventChannelAdmin/ConsumerAdmin/obtain_pull_supplier
       {
         hoshen.xsm.lightsoft.corba.CosEventChannelAdmin.ProxyPullSupplier __result = null;
         __result = this.obtain_pull_supplier ();
         out = $rh.createReply();
         hoshen.xsm.lightsoft.corba.CosEventChannelAdmin.ProxyPullSupplierHelper.write (out, __result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke


} // class _ConsumerAdminPOA
