package hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin;


/**
* hoshen/xsm/lightsoft/corba/CosNotifyChannelAdmin/ConsumerAdmin.java .
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from lightsoft/CosNotifyChannelAdmin.idl
* 13:11:07 GMT+02:00 יום חמישי 28 יוני 2007
*/


/**
    * An interface for consumer administration objects.
    */
public interface ConsumerAdmin extends ConsumerAdminOperations, hoshen.xsm.lightsoft.corba.CosNotification.QoSAdmin, hoshen.xsm.lightsoft.corba.CosNotifyComm.NotifySubscribe, hoshen.xsm.lightsoft.corba.CosNotifyFilter.FilterAdmin, hoshen.xsm.lightsoft.corba.CosEventChannelAdmin.ConsumerAdmin
{
} // interface ConsumerAdmin
