package hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin;


/**
* hoshen/xsm/lightsoft/corba/CosNotifyChannelAdmin/EventChannelFactoryOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from lightsoft/CosNotifyChannelAdmin.idl
* 13:11:07 GMT+02:00 יום חמישי 28 יוני 2007
*/


/**
    * An interface for the event channel factory.
    */
public interface EventChannelFactoryOperations 
{

  /**
       * Create an event channel with specified quality of service.
       * @parm <code>initial_qos</code> - A list of name-value pair that
       * specify the desired quality of service settings for this event
       * channel.
       * @parm <code>initial_admin</code> - A list of name-value pair that
       * specify the desired administrative settings for this event channel.
       * @returns A new event channel object reference.
       * @raises UnsupportedQoS If any of the settings in the
       * <code>initial_qos</code> sequence could not be supported.
       * @raises UnsupportedAdmin If any of the settings in the
       * <code>initial_admin</code> sequence could not be supported.
       */
  hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin.EventChannel create_channel (hoshen.xsm.lightsoft.corba.CosNotification.Property[] initial_qos, hoshen.xsm.lightsoft.corba.CosNotification.Property[] initial_admin, org.omg.CORBA.IntHolder id) throws hoshen.xsm.lightsoft.corba.CosNotification.UnsupportedQoS, hoshen.xsm.lightsoft.corba.CosNotification.UnsupportedAdmin;

  /**
       * Get all event channels created by this factory.
       * @returns A sequence of channel object unique identifiers.
       */
  int[] get_all_channels ();

  /**
       * Get an event channel object from its ID.
       * @parm <code>id</code> - A unique identifier for the channel object.
       * @returns An <code>EventChannel</code> object reference.
       * @raises ChannelNotFound If no channel object with that ID
       * could be found.
       */
  hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin.EventChannel get_event_channel (int id) throws hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin.ChannelNotFound;
} // interface EventChannelFactoryOperations
