package hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin;


/**
* hoshen/xsm/lightsoft/corba/CosNotifyChannelAdmin/ObtainInfoModeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from lightsoft/CosNotifyChannelAdmin.idl
* 13:11:01 GMT+02:00 יום חמישי 28 יוני 2007
*/


/**
    * Enumeration of modes for obtaining subscription or offered types.
    */
abstract public class ObtainInfoModeHelper
{
  private static String  _id = "IDL:omg.org/CosNotifyChannelAdmin/ObtainInfoMode:1.0";

  public static void insert (org.omg.CORBA.Any a, hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin.ObtainInfoMode that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin.ObtainInfoMode extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin.ObtainInfoModeHelper.id (), "ObtainInfoMode", new String[] { "ALL_NOW_UPDATES_OFF", "ALL_NOW_UPDATES_ON", "NONE_NOW_UPDATES_OFF", "NONE_NOW_UPDATES_ON"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin.ObtainInfoMode read (org.omg.CORBA.portable.InputStream istream)
  {
    return hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin.ObtainInfoMode.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin.ObtainInfoMode value)
  {
    ostream.write_long (value.value ());
  }

}
