package hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin;


/**
* hoshen/xsm/lightsoft/corba/CosNotifyChannelAdmin/ProxyPullConsumer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from lightsoft/CosNotifyChannelAdmin.idl
* 13:11:05 GMT+02:00 יום חמישי 28 יוני 2007
*/


/**
    * An interface for proxy pull consumers.
    */
public interface ProxyPullConsumer extends ProxyPullConsumerOperations, hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin.ProxyConsumer, hoshen.xsm.lightsoft.corba.CosNotifyComm.PullConsumer
{
} // interface ProxyPullConsumer
