package hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin;


/**
* hoshen/xsm/lightsoft/corba/CosNotifyChannelAdmin/ProxyPushSupplier.java .
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from lightsoft/CosNotifyChannelAdmin.idl
* 13:11:05 GMT+02:00 יום חמישי 28 יוני 2007
*/


/**
    * An interface for proxy push suppliers.
    */
public interface ProxyPushSupplier extends ProxyPushSupplierOperations, hoshen.xsm.lightsoft.corba.CosNotifyChannelAdmin.ProxySupplier, hoshen.xsm.lightsoft.corba.CosNotifyComm.PushSupplier
{
} // interface ProxyPushSupplier
