package hoshen.xsm.lightsoft.corba.CosNotifyComm;


/**
* hoshen/xsm/lightsoft/corba/CosNotifyComm/PullSupplierPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from lightsoft/CosNotifyComm.idl
* 13:11:11 GMT+02:00 יום חמישי 28 יוני 2007
*/


/**
    * An interface for pull suppliers.
    */
public class PullSupplierPOATie extends PullSupplierPOA
{

  private hoshen.xsm.lightsoft.corba.CosNotifyComm.PullSupplierOperations _delegate;
  private org.omg.PortableServer.POA _poa;
  // Constructors
  public PullSupplierPOATie (hoshen.xsm.lightsoft.corba.CosNotifyComm.PullSupplierOperations delegate) {
     this._delegate = delegate;
  }

  public PullSupplierPOATie (hoshen.xsm.lightsoft.corba.CosNotifyComm.PullSupplierOperations delegate,
     org.omg.PortableServer.POA poa) {
     this._delegate = delegate;
     this._poa = poa;
  }

  public hoshen.xsm.lightsoft.corba.CosNotifyComm.PullSupplierOperations _delegate() {
     return this._delegate;
  }

  public void _delegate(
     hoshen.xsm.lightsoft.corba.CosNotifyComm.PullSupplierOperations delegate) {
     this._delegate = delegate;
  }

  public org.omg.PortableServer.POA _default_POA() {
     if(_poa != null) {
        return _poa;
     } else {
        return super._default_POA();
     }
  }


  /**
       * Indicates that a consumer is changing the names of the types of
       * events it is subscribed to.
       * @parm <code>added</code> - The event types added.
       * @parm <code>removed</code> - The event types removed.
       * @raises InvalidEventType If any of the event type names in either 
       * the of the input sequences are invalid.
       */
  public void subscription_change (hoshen.xsm.lightsoft.corba.CosNotification.EventType[] added, hoshen.xsm.lightsoft.corba.CosNotification.EventType[] removed) throws hoshen.xsm.lightsoft.corba.CosNotifyComm.InvalidEventType
  {
    _delegate.subscription_change(added, removed);
    return;
  } // subscription_change


  /**
       * Pull an event from this supplier
       * @returns The event.
       * @raises Disconnected If this supplier is disconnected.
       */
  public org.omg.CORBA.Any pull () throws hoshen.xsm.lightsoft.corba.CosEventComm.Disconnected
  {
    return _delegate.pull();
  } // pull


  /**
       * Try to pull an event from this supplier.
       * @parm <code>has_event</code> - boolean indicating if supplier
       * has an event.
       * @returns The event if <code>has_event</code> is true.
       * @raises Disconnected If this supplier is disconnected.
       */
  public org.omg.CORBA.Any try_pull (org.omg.CORBA.BooleanHolder has_event) throws hoshen.xsm.lightsoft.corba.CosEventComm.Disconnected
  {
    return _delegate.try_pull(has_event);
  } // try_pull


  /**
       * Disconnect a pull supplier.
       */
  public void disconnect_pull_supplier ()
  {
    _delegate.disconnect_pull_supplier();
    return;
  } // disconnect_pull_supplier


} // class PullSupplierPOATie
