package hoshen.xsm.lightsoft.corba.CosNotifyComm;


/**
* hoshen/xsm/lightsoft/corba/CosNotifyComm/PullConsumerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from lightsoft/CosNotifyComm.idl
* 13:11:11 GMT+02:00 יום חמישי 28 יוני 2007
*/


/**
    * An interface for pull consumers.
    */
public interface PullConsumerOperations  extends hoshen.xsm.lightsoft.corba.CosNotifyComm.NotifyPublishOperations, hoshen.xsm.lightsoft.corba.CosEventComm.PullConsumerOperations
{
} // interface PullConsumerOperations
