package hoshen.xsm.lightsoft.corba.CosNotifyComm;


/**
* hoshen/xsm/lightsoft/corba/CosNotifyComm/SequencePullConsumerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from lightsoft/CosNotifyComm.idl
* 13:11:11 GMT+02:00 יום חמישי 28 יוני 2007
*/


/**
    * An interface for sequences pull consumers.
    */
public interface SequencePullConsumerOperations  extends hoshen.xsm.lightsoft.corba.CosNotifyComm.NotifyPublishOperations
{

  /**
       * Disconnect this pull consumer.
       */
  void disconnect_sequence_pull_consumer ();
} // interface SequencePullConsumerOperations
