package hoshen.xsm.lightsoft.corba.CosNotifyComm;


/**
* hoshen/xsm/lightsoft/corba/CosNotifyComm/SequencePushSupplier.java .
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from lightsoft/CosNotifyComm.idl
* 13:11:12 GMT+02:00 יום חמישי 28 יוני 2007
*/


/**
    * An interface for sequences push suppliers.
    */
public interface SequencePushSupplier extends SequencePushSupplierOperations, hoshen.xsm.lightsoft.corba.CosNotifyComm.NotifySubscribe, org.omg.CORBA.portable.IDLEntity 
{
} // interface SequencePushSupplier
