package hoshen.xsm.lightsoft.corba.CosNotifyComm;


/**
* hoshen/xsm/lightsoft/corba/CosNotifyComm/StructuredPullConsumer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from lightsoft/CosNotifyComm.idl
* 13:11:11 GMT+02:00 יום חמישי 28 יוני 2007
*/


/**
    * An interface for structured pull consumers.
    */
public interface StructuredPullConsumer extends StructuredPullConsumerOperations, hoshen.xsm.lightsoft.corba.CosNotifyComm.NotifyPublish, org.omg.CORBA.portable.IDLEntity 
{
} // interface StructuredPullConsumer
