// Skeleton class generated by rmic, do not edit.
// Contents subject to change without notice.


public final class Hello7Server_Skel
    extends java.lang.Object
    implements java.rmi.server.Skeleton
{
    private static java.rmi.server.Operation[] operations = {
        new java.rmi.server.Operation("java.util.Date getTime()"), 
        new java.rmi.server.Operation("java.lang.String printHello()")
    };
    
    private static final long interfaceHash = 4600289229433332260L;
    
    public java.rmi.server.Operation[] getOperations() { 
        return operations;
    }
    
    public void dispatch(java.rmi.Remote obj, java.rmi.server.RemoteCall call, int opnum, long hash) throws java.rmi.RemoteException, Exception {
        // Exceptions pass through, to be caught, identified and marshalled
        
        if (hash != interfaceHash)
            throw new java.rmi.server.SkeletonMismatchException("Hash mismatch");
        Hello7Server server = (Hello7Server)obj;
        switch (opnum) {
        case 0: { // getTime
            call.releaseInputStream();
            java.util.Date $result = server.getTime();
            try {
                java.io.ObjectOutput out = call.getResultStream(true);
                out.writeObject($result);
            } catch (java.io.IOException ex) {
                throw new java.rmi.MarshalException("Error marshaling return", ex);
            };
            break;
            }
        
        case 1: { // printHello
            call.releaseInputStream();
            java.lang.String $result = server.printHello();
            try {
                java.io.ObjectOutput out = call.getResultStream(true);
                out.writeObject($result);
            } catch (java.io.IOException ex) {
                throw new java.rmi.MarshalException("Error marshaling return", ex);
            };
            break;
            }
        default:
            throw new java.rmi.RemoteException("Method number out of range");
        }
    }
}
