package hoshen.xsm.lightsoft.corba.CosTrading;


/**
* hoshen/xsm/lightsoft/corba/CosTrading/ImportAttributesOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from lightsoft/CosTrading.idl
* 13:11:18 GMT+02:00 יום חמישי 28 יוני 2007
*/


/** This interface contains attributes that describe
 * policies used witin the trader when resolving queries.
 */
public interface ImportAttributesOperations 
{
  int def_search_card ();
  int max_search_card ();
  int def_match_card ();
  int max_match_card ();
  int def_return_card ();
  int max_return_card ();
  int max_list ();
  int def_hop_count ();
  int max_hop_count ();
  hoshen.xsm.lightsoft.corba.CosTrading.FollowOption def_follow_policy ();
  hoshen.xsm.lightsoft.corba.CosTrading.FollowOption max_follow_policy ();
} // interface ImportAttributesOperations
