package hoshen.xsm.lightsoft.corba.CosTrading;


/**
* hoshen/xsm/lightsoft/corba/CosTrading/ImportAttributesPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from lightsoft/CosTrading.idl
* 13:11:18 GMT+02:00 יום חמישי 28 יוני 2007
*/


/** This interface contains attributes that describe
 * policies used witin the trader when resolving queries.
 */
public abstract class ImportAttributesPOA extends org.omg.PortableServer.Servant
                implements hoshen.xsm.lightsoft.corba.CosTrading.ImportAttributesOperations, org.omg.CORBA.portable.InvokeHandler
{

  public hoshen.xsm.lightsoft.corba.CosTrading.ImportAttributes _this() {
     return hoshen.xsm.lightsoft.corba.CosTrading.ImportAttributesHelper.narrow(
        super._this_object());
  }

  public hoshen.xsm.lightsoft.corba.CosTrading.ImportAttributes _this(org.omg.CORBA.ORB orb) {
     return hoshen.xsm.lightsoft.corba.CosTrading.ImportAttributesHelper.narrow(
        super._this_object(orb));
  }

  public String[] _all_interfaces(
     org.omg.PortableServer.POA poa,
     byte[] objectId) {
         return (String[])__ids.clone();
  }

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:omg.org/CosTrading/ImportAttributes:1.0"};

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_def_search_card", new java.lang.Integer (0));
    _methods.put ("_get_max_search_card", new java.lang.Integer (1));
    _methods.put ("_get_def_match_card", new java.lang.Integer (2));
    _methods.put ("_get_max_match_card", new java.lang.Integer (3));
    _methods.put ("_get_def_return_card", new java.lang.Integer (4));
    _methods.put ("_get_max_return_card", new java.lang.Integer (5));
    _methods.put ("_get_max_list", new java.lang.Integer (6));
    _methods.put ("_get_def_hop_count", new java.lang.Integer (7));
    _methods.put ("_get_max_hop_count", new java.lang.Integer (8));
    _methods.put ("_get_def_follow_policy", new java.lang.Integer (9));
    _methods.put ("_get_max_follow_policy", new java.lang.Integer (10));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // CosTrading/ImportAttributes/_get_def_search_card
       {
         int __result = (int)0;
         __result = this.def_search_card ();
         out = $rh.createReply();
         out.write_ulong (__result);
         break;
       }

       case 1:  // CosTrading/ImportAttributes/_get_max_search_card
       {
         int __result = (int)0;
         __result = this.max_search_card ();
         out = $rh.createReply();
         out.write_ulong (__result);
         break;
       }

       case 2:  // CosTrading/ImportAttributes/_get_def_match_card
       {
         int __result = (int)0;
         __result = this.def_match_card ();
         out = $rh.createReply();
         out.write_ulong (__result);
         break;
       }

       case 3:  // CosTrading/ImportAttributes/_get_max_match_card
       {
         int __result = (int)0;
         __result = this.max_match_card ();
         out = $rh.createReply();
         out.write_ulong (__result);
         break;
       }

       case 4:  // CosTrading/ImportAttributes/_get_def_return_card
       {
         int __result = (int)0;
         __result = this.def_return_card ();
         out = $rh.createReply();
         out.write_ulong (__result);
         break;
       }

       case 5:  // CosTrading/ImportAttributes/_get_max_return_card
       {
         int __result = (int)0;
         __result = this.max_return_card ();
         out = $rh.createReply();
         out.write_ulong (__result);
         break;
       }

       case 6:  // CosTrading/ImportAttributes/_get_max_list
       {
         int __result = (int)0;
         __result = this.max_list ();
         out = $rh.createReply();
         out.write_ulong (__result);
         break;
       }

       case 7:  // CosTrading/ImportAttributes/_get_def_hop_count
       {
         int __result = (int)0;
         __result = this.def_hop_count ();
         out = $rh.createReply();
         out.write_ulong (__result);
         break;
       }

       case 8:  // CosTrading/ImportAttributes/_get_max_hop_count
       {
         int __result = (int)0;
         __result = this.max_hop_count ();
         out = $rh.createReply();
         out.write_ulong (__result);
         break;
       }

       case 9:  // CosTrading/ImportAttributes/_get_def_follow_policy
       {
         hoshen.xsm.lightsoft.corba.CosTrading.FollowOption __result = null;
         __result = this.def_follow_policy ();
         out = $rh.createReply();
         hoshen.xsm.lightsoft.corba.CosTrading.FollowOptionHelper.write (out, __result);
         break;
       }

       case 10:  // CosTrading/ImportAttributes/_get_max_follow_policy
       {
         hoshen.xsm.lightsoft.corba.CosTrading.FollowOption __result = null;
         __result = this.max_follow_policy ();
         out = $rh.createReply();
         hoshen.xsm.lightsoft.corba.CosTrading.FollowOptionHelper.write (out, __result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke


} // class _ImportAttributesPOA
