package hoshen.xsm.lightsoft.corba.CosTrading;


/**
* hoshen/xsm/lightsoft/corba/CosTrading/UnknownMaxLeft.java .
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from lightsoft/CosTrading.idl
* 13:11:18 GMT+02:00 יום חמישי 28 יוני 2007
*/

public final class UnknownMaxLeft extends org.omg.CORBA.UserException implements org.omg.CORBA.portable.IDLEntity
{

  public UnknownMaxLeft ()
  {
    super(UnknownMaxLeftHelper.id());
  } // ctor

  public UnknownMaxLeft (String $reason)
  {
    super(UnknownMaxLeftHelper.id() + "  " + $reason);
  } // ctor

} // class UnknownMaxLeft
