/*  COLOR DEFINITIONS  HEADER FILE
    THIS   HEADER FILE WILL MAKE USING TURBO C ' S   TEXTATTRIBUTE FEATURE
    MUCH EASIER TO USE                                                        */

#ifndef _COLORS_H
#define _COLORS_H


/*  ------------------------------------------------------------------------- */
/*   BLACK BACKGROUND     */
/*  ------------------------------------------------------------------------- */

#define  BLACK                            0
#define  BLUE                             1
#define  GREEN                            2
#define  CYAN                             3
#define  RED                              4
#define  MAGNETA                          5
#define  BROWN                            6
#define  LIGHTGRAY                        7
#define  DARKGRAY                         8
#define  LIGHTBLUE                        9
#define  LIGHTGREEN                      10
#define  LIGHTCYAN                       11
#define  LIGHTRED                        12
#define  LIGHTMAGNETA                    13
#define  YELLOW                          14
#define  WHITE                           15


/*  ------------------------------------------------------------------------- */
/*  BLUE BACK GROUND   */
/*  ------------------------------------------------------------------------- */

#define  BLACK_ON_BLUE                   16
#define  BLUE_ON_BLUE                    17
#define  GREEN_ON_BLUE                   18
#define  CYAN_ON_BLUE                    19
#define  RED_ON_BLUE                     20
#define  MAGNETA_ON_BLUE                 21
#define  BROWN_ON_BLUE                   22
#define  LIGHTGRAY_ON_BLUE               23
#define  DARKGRAY_ON_BLUE                24
#define  LIGHTBLUE_ON_BLUE               25
#define  LIGHTGREEN_ON_BLUE              26
#define  LIGHTCYAN_ON_BLUE               27
#define  LIGHTRED_ON_BLUE                28
#define  LIGHTMAGNETA_ON_BLUE            29
#define  YELLOW_ON_BLUE                  30
#define  WHITE_ON_BLUE                   31


/*  ------------------------------------------------------------------------- */
/*      GREEN   BACKGROUND                                                    */
/*  ------------------------------------------------------------------------- */

#define  BLACK_ON_GREEN                  32
#define  BLUE_ON_GREEN                   33
#define  GREEN_ON_GREEN                  34
#define  CYAN_ON_GREEN                   35
#define  RED_ON_GREEN                    36
#define  MAGNETA_ON_GREEN                37
#define  BROWN_ON_GREEN                  38
#define  LIGHTGRAY_ON_GREEN              39
#define  DARKGRAY_ON_GREEN               40
#define  LIGHTBLUE_ON_GREEN              41
#define  LIGHTGREEN_ON_GREEN             42
#define  LIGHTCYAN_ON_GREEN              43
#define  LIGHTRED_ON_GREEN               44
#define  LIGHTMAGNETA_ON_GREEN           45
#define  YELLOW_ON_GREEN                 46
#define  WHITE_ON_GREEN                  47

/*  ------------------------------------------------------------------------- */
/*      CYAN BACKGOUND                   */

/*  ------------------------------------------------------------------------- */
#define  BLACK_ON_CYAN                   48
#define  BLUE_ON_CYAN                    49
#define  GREEN_ON_CYAN                   50
#define  CYAN_ON_CYAN                    51
#define  RED_ON_CYAN                     52
#define  MAGNETA_ON_CYAN                 53
#define  BROWN_ON_CYAN                   54
#define  LIGHTGRAY_ON_CYAN               55
#define  DARKGRAY_ON_CYAN                56
#define  LIGHTBLUE_ON_CYAN               57
#define  LIGHTGREEN_ON_CYAN              58
#define  LIGHTCYAN_ON_CYAN               59
#define  LIGHTRED_ON_CYAN                60
#define  LIGHTMAGNETA_ON_CYAN            61
#define  YELLOW_ON_CYAN                  62
#define  WHITE_ON_CYAN                   63

/*  ------------------------------------------------------------------------- */
/*              RED BACKGROUND                                                */
/*  ------------------------------------------------------------------------- */
#define  BLACK_ON_RED                    64
#define  BLUE_ON_RED                     65
#define  GREEN_ON_RED                    66
#define  CYAN_ON_RED                     67
#define  RED_ON_RED                      68
#define  MAGNETA_ON_RED                  69
#define  BROWN_ON_RED                    70
#define  LIGHTGRAY_ON_RED                71
#define  DARKGRAY_ON_RED                 72
#define  LIGHTBLUE_ON_RED                73
#define  LIGHTGREEN_ON_RED               74
#define  LIGHTCYAN_ON_RED                75
#define  LIGHTRED_ON_RED                 76
#define  LIGHTMAGNETA_ON_RED             77
#define  YELLOW_ON_RED                   78
#define  WHITE_ON_RED                    79


/*  ------------------------------------------------------------------------- */
/*      MAGNETA  BACKGROUND                                                   */
/*  ------------------------------------------------------------------------- */

#define  BLACK_ON_MAGNETA                80
#define  BLUE_ON_MAGNETA                 81
#define  GREEN_ON_MAGNETA                82
#define  CYAN_ON_MAGNETA                 83
#define  RED_ON_MAGNETA                  84
#define  MAGNETA_ON_MAGNETA              85
#define  BROWN_ON_MAGNETA                86
#define  LIGHTGRAY_ON_MAGNETA            87
#define  DARKGRAY_ON_MAGNETA             88
#define  LIGHTBLUE_ON_MAGNETA            89
#define  LIGHTGREEN_ON_MAGNETA           90
#define  LIGHTCYAN_ON_MAGNETA            91
#define  LIGHTRED_ON_MAGNETA             92
#define  LIGHTMAGNETA_ON_MAGNETA         93
#define  YELLOW_ON_MAGNETA               94
#define  WHITE_ON_MAGNETA                95


/*  ------------------------------------------------------------------------- */
/*      BROWN    BACKGROUND                                                   */
/*  ------------------------------------------------------------------------- */

#define  BLACK_ON_BROWN                  96
#define  BLUE_ON_BROWN                   97
#define  GREEN_ON_BROWN                  98
#define  CYAN_ON_BROWN                   99
#define  RED_ON_BROWN                   100
#define  MAGNETA_ON_BROWN               101
#define  BROWN_ON_BROWN                 102
#define  LIGHTGRAY_ON_BROWN             103
#define  DARKGRAY_ON_BROWN              104
#define  LIGHTBLUE_ON_BROWN             105
#define  LIGHTGREEN_ON_BROWN            106
#define  LIGHTCYAN_ON_BROWN             107
#define  LIGHTRED_ON_BROWN              108
#define  LIGHTMAGNETA_ON_BROWN          109
#define  YELLOW_ON_BROWN                110
#define  WHITE_ON_BROWN                 111

/*  ------------------------------------------------------------------------- */
/*     LIGHTGRAY   BACKGROUND                                                 */
/*  ------------------------------------------------------------------------- */

#define  BLACK_ON_LIGHTGRAY             112
#define  BLUE_ON_LIGHTGRAY              113
#define  GREEN_ON_LIGHTGRAY             114
#define  CYAN_ON_LIGHTGRAY              115
#define  RED_ON_LIGHTGRAY               116
#define  MAGNETA_ON_LIGHTGRAY           117
#define  BROWN_ON_LIGHTGRAY             118
#define  LIGHTGRAY_ON_LIGHTGRAY         119
#define  DARKGRAY_ON_LIGHTGRAY          120
#define  LIGHTBLUE_ON_LIGHTGRAY         121
#define  LIGHTGREEN_ON_LIGHTGRAY        122
#define  LIGHTCYAN_ON_LIGHTGRAY         123
#define  LIGHTRED_ON_LIGHTGRAY          124
#define  LIGHTMAGNETA_ON_LIGHTGRAY      125
#define  YELLOW_ON_LIGHTGRAY            126
#define  WHITE_ON_LIGHTGRAY             127

/*  ------------------------------------------------------------------------- */

/* ---------------------------------------------------------------------------*/
/*    box  characters definitions for single & double boxes                   */
/* ---------------------------------------------------------------------------*/

#define  S_UL_CORNER                    218
#define  S_UR_CORNER                    191
#define  S_LL_CORNER                    192
#define  S_LR_CORNER                    217
#define  S_LINE                         179
#define  D_UL_CORNER                    201
#define  D_UR_CORNER                    187
#define  D_LL_CORNER                    200
#define  D_LR_CORNER                    188
#define  D_LINE                         186

/*  ------------------------------------------------------------------------- */
#endif
