package hoshen.xsm.lightsoft.corba.CosNotification;


/**
* hoshen/xsm/lightsoft/corba/CosNotification/EventHeader.java .
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from lightsoft/CosNotification.idl
* 13:10:58 GMT+02:00 יום חמישי 28 יוני 2007
*/


/**
    * The event header. A two-tuple consisting of the fixed header
    * and an optional header.
    */
public final class EventHeader implements org.omg.CORBA.portable.IDLEntity
{
  public hoshen.xsm.lightsoft.corba.CosNotification.FixedEventHeader fixed_header = null;
  public hoshen.xsm.lightsoft.corba.CosNotification.Property variable_header[] = null;

  public EventHeader ()
  {
  } // ctor

  public EventHeader (hoshen.xsm.lightsoft.corba.CosNotification.FixedEventHeader _fixed_header, hoshen.xsm.lightsoft.corba.CosNotification.Property[] _variable_header)
  {
    fixed_header = _fixed_header;
    variable_header = _variable_header;
  } // Init ctor

} // class EventHeader
