package hoshen.xsm.lightsoft.corba.CosNotification;


/**
* hoshen/xsm/lightsoft/corba/CosNotification/FixedEventHeader.java .
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from lightsoft/CosNotification.idl
* 13:10:58 GMT+02:00 יום חמישי 28 יוני 2007
*/


/**
    * The fixed header part of an event. A two-tuple consisting of an
    * <code>EventType</code> structure and the event name.
    */
public final class FixedEventHeader implements org.omg.CORBA.portable.IDLEntity
{
  public hoshen.xsm.lightsoft.corba.CosNotification.EventType event_type = null;
  public String event_name = "";

  public FixedEventHeader ()
  {
  } // ctor

  public FixedEventHeader (hoshen.xsm.lightsoft.corba.CosNotification.EventType _event_type, String _event_name)
  {
    event_type = _event_type;
    event_name = _event_name;
  } // Init ctor

} // class FixedEventHeader
