package hoshen.xsm.lightsoft.corba.CosNotification;

/**
* hoshen/xsm/lightsoft/corba/CosNotification/FixedEventHeaderHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from lightsoft/CosNotification.idl
* 13:10:58 GMT+02:00 יום חמישי 28 יוני 2007
*/


/**
    * The fixed header part of an event. A two-tuple consisting of an
    * <code>EventType</code> structure and the event name.
    */
public final class FixedEventHeaderHolder implements org.omg.CORBA.portable.Streamable
{
  public hoshen.xsm.lightsoft.corba.CosNotification.FixedEventHeader value = null;

  public FixedEventHeaderHolder ()
  {
  }

  public FixedEventHeaderHolder (hoshen.xsm.lightsoft.corba.CosNotification.FixedEventHeader initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = hoshen.xsm.lightsoft.corba.CosNotification.FixedEventHeaderHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    hoshen.xsm.lightsoft.corba.CosNotification.FixedEventHeaderHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return hoshen.xsm.lightsoft.corba.CosNotification.FixedEventHeaderHelper.type ();
  }

}
