package hoshen.xsm.lightsoft.corba.CosNotification;


/**
* hoshen/xsm/lightsoft/corba/CosNotification/MaxQueueLength.java .
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from lightsoft/CosNotification.idl
* 13:10:58 GMT+02:00 יום חמישי 28 יוני 2007
*/

public interface MaxQueueLength
{

  // message quality of service
  public static final String value = "MaxQueueLength";
}
