package hoshen.xsm.lightsoft.corba.CosNotification;


/**
* hoshen/xsm/lightsoft/corba/CosNotification/StopTimeSupported.java .
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from lightsoft/CosNotification.idl
* 13:10:58 GMT+02:00 יום חמישי 28 יוני 2007
*/

public interface StopTimeSupported
{

  // StartTimeSupported takes on a boolean value
  public static final String value = "StopTimeSupported";
}
